/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress, Dictionary, BitString } from '@ton/core';

// === BounceMode ===
export enum BounceMode {
    NoBounce = 0,
    Only256BitsOfBody = 1,
    RichBounce = 2,
    RichBounceOnlyRootCell = 3
}

// === Color ===
export enum Color {
    Red = 0,
    Green = 1,
    Blue = 2
}

// === EInt9 ===
export enum EInt9 {
    P133 = 133,
    M1 = -1
}

// === EUint6 ===
export enum EUint6 {
    P63 = 63,
    P30 = 30,
    P1 = 1
}

// === EUint1 ===
export enum EUint1 {
    A = 0,
    B = 1
}

// === EInt1 ===
export enum EInt1 {
    A = -1,
    B = 0
}

// === EUint123 ===
export enum EUint123 {
    Z = 0,
    V5 = 5,
    E123 = 5316911983139663491615228241121378304,
    E123_2 = 7975367974709495237422842361682067456
}

// === contract ===
export interface contract {
}

export function loadcontract(slice: Slice): contract {
    return {
    };
}

export function storecontract(src: contract): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === blockchain ===
export interface blockchain {
}

export function loadblockchain(slice: Slice): blockchain {
    return {
    };
}

export function storeblockchain(src: blockchain): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === PackOptions ===
export interface PackOptions {
    skipBitsNValidation: boolean;
}

export function loadPackOptions(slice: Slice): PackOptions {
    const skipBitsNValidation = slice.loadBoolean();
    return {
        skipBitsNValidation,
    };
}

export function storePackOptions(src: PackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.skipBitsNValidation);
    };
}

// === UnpackOptions ===
export interface UnpackOptions {
    assertEndAfterReading: boolean;
    throwIfOpcodeDoesNotMatch: bigint;
}

export function loadUnpackOptions(slice: Slice): UnpackOptions {
    const assertEndAfterReading = slice.loadBoolean();
    const throwIfOpcodeDoesNotMatch = slice.loadIntBig(257);
    return {
        assertEndAfterReading,
        throwIfOpcodeDoesNotMatch,
    };
}

export function storeUnpackOptions(src: UnpackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.assertEndAfterReading);
        builder.storeInt(src.throwIfOpcodeDoesNotMatch, 257);
    };
}

// === random ===
export interface random {
}

export function loadrandom(slice: Slice): random {
    return {
    };
}

export function storerandom(src: random): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === debug ===
export interface debug {
}

export function loaddebug(slice: Slice): debug {
    return {
    };
}

export function storedebug(src: debug): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === ContractState ===
export interface ContractState {
    code: Cell;
    data: Cell;
}

export function loadContractState(slice: Slice): ContractState {
    const code = slice.loadRef();
    const data = slice.loadRef();
    return {
        code,
        data,
    };
}

export function storeContractState(src: ContractState): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.code);
        builder.storeRef(src.data);
    };
}

// === AddressShardingOptions ===
export interface AddressShardingOptions {
    fixedPrefixLength: number;
    closeTo: Address;
}

export function loadAddressShardingOptions(slice: Slice): AddressShardingOptions {
    const fixedPrefixLength = slice.loadUint(5);
    const closeTo = slice.loadAddress();
    return {
        fixedPrefixLength,
        closeTo,
    };
}

export function storeAddressShardingOptions(src: AddressShardingOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.fixedPrefixLength, 5);
        builder.storeAddress(src.closeTo);
    };
}

// === AutoDeployAddress ===
export interface AutoDeployAddress {
    workchain: number;
    stateInit: ContractState | Cell;
    toShard: AddressShardingOptions | null;
}

export function loadAutoDeployAddress(slice: Slice): AutoDeployAddress {
    const workchain = slice.loadInt(8);
    const stateInit = /* union load - check opcodes */;
    const toShard = /* complex nullable: AddressShardingOptions | null */;
    return {
        workchain,
        stateInit,
        toShard,
    };
}

export function storeAutoDeployAddress(src: AutoDeployAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.workchain, 8);
        /* union store - switch on $$type */;
        /* complex nullable store */;
    };
}

// === ExtOutLogBucket ===
export const ExtOutLogBucketOpcode = 0x0;

export interface ExtOutLogBucket {
    readonly $$type: 'ExtOutLogBucket';
    topic: bigint | Buffer;
}

export function loadExtOutLogBucket(slice: Slice): ExtOutLogBucket {
    if (slice.loadUint(8) !== 0x0) {
        throw new Error('Invalid opcode for ExtOutLogBucket');
    }
    const topic = /* union load - check opcodes */;
    return {
        $$type: 'ExtOutLogBucket',
        topic,
    };
}

export function storeExtOutLogBucket(src: ExtOutLogBucket): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x0, 8);
        /* union store - switch on $$type */;
    };
}

// === OutMessage ===
export interface OutMessage {
    messageCell: Cell;
}

export function loadOutMessage(slice: Slice): OutMessage {
    const messageCell = slice.loadRef();
    return {
        messageCell,
    };
}

export function storeOutMessage(src: OutMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.messageCell);
    };
}

// === StateInit ===
export interface StateInit {
    fixedPrefixLength: number | null;
    special: unknown /* (bool, bool) */ | null;
    code: Cell | null;
    data: Cell | null;
    library: Cell | null;
}

export function loadStateInit(slice: Slice): StateInit {
    const fixedPrefixLength = slice.loadBit() ? slice.loadUint(5) : null;
    const special = /* complex nullable: unknown /* (bool, bool) */ | null */;
    const code = slice.loadMaybeRef();
    const data = slice.loadMaybeRef();
    const library = slice.loadMaybeRef();
    return {
        fixedPrefixLength,
        special,
        code,
        data,
        library,
    };
}

export function storeStateInit(src: StateInit): (builder: Builder) => void {
    return (builder: Builder) => {
        src.fixedPrefixLength !== null ? (builder.storeBit(true), builder.storeUint(src.fixedPrefixLength, 5)) : builder.storeBit(false);
        /* complex nullable store */;
        builder.storeMaybeRef(src.code);
        builder.storeMaybeRef(src.data);
        builder.storeMaybeRef(src.library);
    };
}

// === InMessage ===
export interface InMessage {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    body: Slice;
}

export function loadInMessage(slice: Slice): InMessage {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const body = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        body,
    };
}

export function storeInMessage(src: InMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.body);
    };
}

// === InMessageBounced ===
export interface InMessageBounced {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    bouncedBody: Slice;
}

export function loadInMessageBounced(slice: Slice): InMessageBounced {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const bouncedBody = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        bouncedBody,
    };
}

export function storeInMessageBounced(src: InMessageBounced): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.bouncedBody);
    };
}

// === RichBounceBody ===
export const RichBounceBodyOpcode = 0xfffffffe;

export interface RichBounceBody {
    readonly $$type: 'RichBounceBody';
    originalBody: Cell;
    originalInfo: Cell;
    bouncedByPhase: number;
    exitCode: number;
    computePhase: RichBounceComputePhaseInfo | null;
}

export function loadRichBounceBody(slice: Slice): RichBounceBody {
    if (slice.loadUint(32) !== 0xfffffffe) {
        throw new Error('Invalid opcode for RichBounceBody');
    }
    const originalBody = slice.loadRef();
    const originalInfo = slice.loadRef();
    const bouncedByPhase = slice.loadUint(8);
    const exitCode = slice.loadInt(32);
    const computePhase = /* complex nullable: RichBounceComputePhaseInfo | null */;
    return {
        $$type: 'RichBounceBody',
        originalBody,
        originalInfo,
        bouncedByPhase,
        exitCode,
        computePhase,
    };
}

export function storeRichBounceBody(src: RichBounceBody): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0xfffffffe, 32);
        builder.storeRef(src.originalBody);
        builder.storeRef(src.originalInfo);
        builder.storeUint(src.bouncedByPhase, 8);
        builder.storeInt(src.exitCode, 32);
        /* complex nullable store */;
    };
}

// === RichBounceComputePhaseInfo ===
export interface RichBounceComputePhaseInfo {
    gasUsed: number;
    vmSteps: number;
}

export function loadRichBounceComputePhaseInfo(slice: Slice): RichBounceComputePhaseInfo {
    const gasUsed = slice.loadUint(32);
    const vmSteps = slice.loadUint(32);
    return {
        gasUsed,
        vmSteps,
    };
}

export function storeRichBounceComputePhaseInfo(src: RichBounceComputePhaseInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.gasUsed, 32);
        builder.storeUint(src.vmSteps, 32);
    };
}

// === RichBounceOriginalMsgInfo ===
export interface RichBounceOriginalMsgInfo {
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    createdLt: bigint;
    createdAt: number;
}

export function loadRichBounceOriginalMsgInfo(slice: Slice): RichBounceOriginalMsgInfo {
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    return {
        valueCoins,
        valueExtra,
        createdLt,
        createdAt,
    };
}

export function storeRichBounceOriginalMsgInfo(src: RichBounceOriginalMsgInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
    };
}

// === JustInt32 ===
export interface JustInt32 {
    value: number;
}

export function loadJustInt32(slice: Slice): JustInt32 {
    const value = slice.loadInt(32);
    return {
        value,
    };
}

export function storeJustInt32(src: JustInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 32);
    };
}

// === JustMaybeInt32 ===
export interface JustMaybeInt32 {
    value: number | null;
}

export function loadJustMaybeInt32(slice: Slice): JustMaybeInt32 {
    const value = slice.loadBit() ? slice.loadInt(32) : null;
    return {
        value,
    };
}

export function storeJustMaybeInt32(src: JustMaybeInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        src.value !== null ? (builder.storeBit(true), builder.storeInt(src.value, 32)) : builder.storeBit(false);
    };
}

// === Test3_1 ===
export interface Test3_1 {
    f1: JustInt32;
    f2: JustMaybeInt32;
    f3: JustMaybeInt32;
    f4: JustInt32 | bigint;
}

export function loadTest3_1(slice: Slice): Test3_1 {
    const f1 = loadJustInt32(slice);
    const f2 = loadJustMaybeInt32(slice);
    const f3 = loadJustMaybeInt32(slice);
    const f4 = /* union load - check opcodes */;
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest3_1(src: Test3_1): (builder: Builder) => void {
    return (builder: Builder) => {
        storeJustInt32(src.f1)(builder);
        storeJustMaybeInt32(src.f2)(builder);
        storeJustMaybeInt32(src.f3)(builder);
        /* union store - switch on $$type */;
    };
}

// === Test3_2 ===
export interface Test3_2 {
    f1: Test3_1;
    f2: Test3_1 | null;
    f3: Test3_1 | null;
}

export function loadTest3_2(slice: Slice): Test3_2 {
    const f1 = loadTest3_1(slice);
    const f2 = /* complex nullable: Test3_1 | null */;
    const f3 = /* complex nullable: Test3_1 | null */;
    return {
        f1,
        f2,
        f3,
    };
}

export function storeTest3_2(src: Test3_2): (builder: Builder) => void {
    return (builder: Builder) => {
        storeTest3_1(src.f1)(builder);
        /* complex nullable store */;
        /* complex nullable store */;
    };
}

// === Test4_1 ===
export interface Test4_1 {
    f1: Address;
    f2: Address;
}

export function loadTest4_1(slice: Slice): Test4_1 {
    const f1 = slice.loadAddress();
    const f2 = slice.loadAddress();
    return {
        f1,
        f2,
    };
}

export function storeTest4_1(src: Test4_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.f1);
        builder.storeAddress(src.f2);
    };
}

// === Test4_2 ===
export interface Test4_2 {
    f1: Address | null;
    f2: Address | null;
}

export function loadTest4_2(slice: Slice): Test4_2 {
    const f1 = slice.loadMaybeAddress();
    const f2 = slice.loadMaybeAddress();
    return {
        f1,
        f2,
    };
}

export function storeTest4_2(src: Test4_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.f1);
        builder.storeAddress(src.f2);
    };
}

// === Test4_3 ===
export interface Test4_3 {
    f: unknown /* (Test4_1, Test4_2) */;
}

export function loadTest4_3(slice: Slice): Test4_3 {
    const f = /* unknown type */;
    return {
        f,
    };
}

export function storeTest4_3(src: Test4_3): (builder: Builder) => void {
    return (builder: Builder) => {
        /* unknown type */;
    };
}

// === Test5_1 ===
export interface Test5_1 {
    f1: Cell;
    f2: Cell | null;
    f3: Cell;
    f4: Cell | null;
}

export function loadTest5_1(slice: Slice): Test5_1 {
    const f1 = slice.loadRef();
    const f2 = slice.loadMaybeRef();
    const f3 = slice.loadRef();
    const f4 = slice.loadBit() ? slice.loadRef() : null;
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest5_1(src: Test5_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.f1);
        builder.storeMaybeRef(src.f2);
        builder.storeRef(src.f3);
        src.f4 !== null ? (builder.storeBit(true), builder.storeRef(src.f4)) : builder.storeBit(false);
    };
}

// === Test5_2 ===
export interface Test5_2 {
    f1: Cell | null;
    f2: Cell | null;
    f3: Cell | null;
    f4: Cell | null;
    f5: Cell | null;
    rest: Slice;
}

export function loadTest5_2(slice: Slice): Test5_2 {
    const f1 = slice.loadBit() ? slice.loadRef() : null;
    const f2 = slice.loadBit() ? slice.loadRef() : null;
    const f3 = slice.loadBit() ? slice.loadRef() : null;
    const f4 = slice.loadBit() ? slice.loadRef() : null;
    const f5 = slice.loadBit() ? slice.loadRef() : null;
    const rest = slice.clone();
    return {
        f1,
        f2,
        f3,
        f4,
        f5,
        rest,
    };
}

export function storeTest5_2(src: Test5_2): (builder: Builder) => void {
    return (builder: Builder) => {
        src.f1 !== null ? (builder.storeBit(true), builder.storeRef(src.f1)) : builder.storeBit(false);
        src.f2 !== null ? (builder.storeBit(true), builder.storeRef(src.f2)) : builder.storeBit(false);
        src.f3 !== null ? (builder.storeBit(true), builder.storeRef(src.f3)) : builder.storeBit(false);
        src.f4 !== null ? (builder.storeBit(true), builder.storeRef(src.f4)) : builder.storeBit(false);
        src.f5 !== null ? (builder.storeBit(true), builder.storeRef(src.f5)) : builder.storeBit(false);
        builder.storeSlice(src.rest);
    };
}

// === Test5_3 ===
export interface Test5_3 {
    f1: number | Cell;
    f2: Buffer | Cell;
    f3: Cell | Cell;
    f4: Cell | bigint;
}

export function loadTest5_3(slice: Slice): Test5_3 {
    const f1 = /* union load - check opcodes */;
    const f2 = /* union load - check opcodes */;
    const f3 = /* union load - check opcodes */;
    const f4 = /* union load - check opcodes */;
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest5_3(src: Test5_3): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
    };
}

// === Test6_1 ===
export const Test6_1Opcode = 0x112233;

export interface Test6_1 {
    readonly $$type: 'Test6_1';
    f1: number;
}

export function loadTest6_1(slice: Slice): Test6_1 {
    if (slice.loadUint(32) !== 0x112233) {
        throw new Error('Invalid opcode for Test6_1');
    }
    const f1 = slice.loadInt(32);
    return {
        $$type: 'Test6_1',
        f1,
    };
}

export function storeTest6_1(src: Test6_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x112233, 32);
        builder.storeInt(src.f1, 32);
    };
}

// === Test6_2 ===
export const Test6_2Opcode = 0x2;

export interface Test6_2 {
    readonly $$type: 'Test6_2';
    f1: number | null;
    f2: Cell;
}

export function loadTest6_2(slice: Slice): Test6_2 {
    if (slice.loadUint(4) !== 0x2) {
        throw new Error('Invalid opcode for Test6_2');
    }
    const f1 = slice.loadBit() ? slice.loadInt(32) : null;
    const f2 = slice.loadRef();
    return {
        $$type: 'Test6_2',
        f1,
        f2,
    };
}

export function storeTest6_2(src: Test6_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x2, 4);
        src.f1 !== null ? (builder.storeBit(true), builder.storeInt(src.f1, 32)) : builder.storeBit(false);
        builder.storeRef(src.f2);
    };
}

// === Test7_1 ===
export const Test7_1Opcode = 0x1020;

export interface Test7_1 {
    readonly $$type: 'Test7_1';
}

export function loadTest7_1(slice: Slice): Test7_1 {
    if (slice.loadUint(16) !== 0x1020) {
        throw new Error('Invalid opcode for Test7_1');
    }
    return {
        $$type: 'Test7_1',
    };
}

export function storeTest7_1(src: Test7_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1020, 16);
    };
}

// === Test7_2 ===
export const Test7_2Opcode = 0x1030;

export interface Test7_2 {
    readonly $$type: 'Test7_2';
}

export function loadTest7_2(slice: Slice): Test7_2 {
    if (slice.loadUint(16) !== 0x1030) {
        throw new Error('Invalid opcode for Test7_2');
    }
    return {
        $$type: 'Test7_2',
    };
}

export function storeTest7_2(src: Test7_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1030, 16);
    };
}

// === Test7_3 ===
export const Test7_3Opcode = 0x1040;

export interface Test7_3 {
    readonly $$type: 'Test7_3';
}

export function loadTest7_3(slice: Slice): Test7_3 {
    if (slice.loadUint(16) !== 0x1040) {
        throw new Error('Invalid opcode for Test7_3');
    }
    return {
        $$type: 'Test7_3',
    };
}

export function storeTest7_3(src: Test7_3): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1040, 16);
    };
}

// === Inner8_1 ===
export const Inner8_1Opcode = 0x10;

export interface Inner8_1 {
    readonly $$type: 'Inner8_1';
    ea: Address | ExternalAddress | null;
}

export function loadInner8_1(slice: Slice): Inner8_1 {
    if (slice.loadUint(8) !== 0x10) {
        throw new Error('Invalid opcode for Inner8_1');
    }
    const ea = slice.loadAddressAny();
    return {
        $$type: 'Inner8_1',
        ea,
    };
}

export function storeInner8_1(src: Inner8_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x10, 8);
        builder.storeAddress(src.ea);
    };
}

// === CellInner8_1 ===
export const CellInner8_1Opcode = 0x1;

export interface CellInner8_1 {
    readonly $$type: 'CellInner8_1';
    ref: Cell;
}

export function loadCellInner8_1(slice: Slice): CellInner8_1 {
    if (slice.loadUint(1) !== 0x1) {
        throw new Error('Invalid opcode for CellInner8_1');
    }
    const ref = slice.loadRef();
    return {
        $$type: 'CellInner8_1',
        ref,
    };
}

export function storeCellInner8_1(src: CellInner8_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 1);
        builder.storeRef(src.ref);
    };
}

// === Inner8_2 ===
export interface Inner8_2 {
    t: unknown /* (bits32, int1, coins?) */;
}

export function loadInner8_2(slice: Slice): Inner8_2 {
    const t = /* unknown type */;
    return {
        t,
    };
}

export function storeInner8_2(src: Inner8_2): (builder: Builder) => void {
    return (builder: Builder) => {
        /* unknown type */;
    };
}

// === Test8 ===
export interface Test8 {
    f1: Inner8_1;
    f2: Inner8_2;
    f3: Inner8_1 | null;
    f4: Inner8_2 | null;
    f5: Inner8_1 | CellInner8_1;
}

export function loadTest8(slice: Slice): Test8 {
    const f1 = loadInner8_1(slice);
    const f2 = loadInner8_2(slice);
    const f3 = slice.loadBit() ? loadInner8_1(slice) : null;
    const f4 = /* complex nullable: Inner8_2 | null */;
    const f5 = /* union load - check opcodes */;
    return {
        f1,
        f2,
        f3,
        f4,
        f5,
    };
}

export function storeTest8(src: Test8): (builder: Builder) => void {
    return (builder: Builder) => {
        storeInner8_1(src.f1)(builder);
        storeInner8_2(src.f2)(builder);
        src.f3 !== null ? (builder.storeBit(true), storeInner8_1(src.f3)(builder)) : builder.storeBit(false);
        /* complex nullable store */;
        /* union store - switch on $$type */;
    };
}

// === Test9_bits2 ===
export interface Test9_bits2 {
    f: BitString;
}

export function loadTest9_bits2(slice: Slice): Test9_bits2 {
    const f = slice.loadBits(2);
    return {
        f,
    };
}

export function storeTest9_bits2(src: Test9_bits2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.f);
    };
}

// === Test9_bits4 ===
export interface Test9_bits4 {
    f: BitString;
}

export function loadTest9_bits4(slice: Slice): Test9_bits4 {
    const f = slice.loadBits(4);
    return {
        f,
    };
}

export function storeTest9_bits4(src: Test9_bits4): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.f);
    };
}

// === Test10_1 ===
export interface Test10_1 {
    a: number;
    b: Builder;
}

export function loadTest10_1(slice: Slice): Test10_1 {
    const a = slice.loadInt(32);
    const b = /* cannot load builder */;
    return {
        a,
        b,
    };
}

export function storeTest10_1(src: Test10_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 32);
        builder.storeBuilder(src.b);
    };
}

// === Test11_1 ===
export interface Test11_1 {
    data: BitString;
    next: Cell | null;
}

export function loadTest11_1(slice: Slice): Test11_1 {
    const data = slice.loadBits(1022);
    const next = slice.loadBit() ? slice.loadRef() : null;
    return {
        data,
        next,
    };
}

export function storeTest11_1(src: Test11_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.data);
        src.next !== null ? (builder.storeBit(true), builder.storeRef(src.next)) : builder.storeBit(false);
    };
}

// === Test11_2 ===
export interface Test11_2 {
    self1: Cell;
    self2: Cell;
}

export function loadTest11_2(slice: Slice): Test11_2 {
    const self1 = slice.loadRef();
    const self2 = slice.loadRef();
    return {
        self1,
        self2,
    };
}

export function storeTest11_2(src: Test11_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.self1);
        builder.storeRef(src.self2);
    };
}

// === JustAddress ===
export interface JustAddress {
    a: Address;
}

export function loadJustAddress(slice: Slice): JustAddress {
    const a = slice.loadAddress();
    return {
        a,
    };
}

export function storeJustAddress(src: JustAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.a);
    };
}

// === MapLookupResult<slice> ===
export interface MapLookupResult<slice> {
    isFound: boolean;
}

export function loadMapLookupResult<slice>(slice: Slice): MapLookupResult<slice> {
    const isFound = slice.loadBoolean();
    return {
        isFound,
    };
}

export function storeMapLookupResult<slice>(src: MapLookupResult<slice>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.isFound);
    };
}

// === Cell<RichBounceOriginalMsgInfo> ===
export interface Cell<RichBounceOriginalMsgInfo> {
}

export function loadCell<RichBounceOriginalMsgInfo>(slice: Slice): Cell<RichBounceOriginalMsgInfo> {
    return {
    };
}

export function storeCell<RichBounceOriginalMsgInfo>(src: Cell<RichBounceOriginalMsgInfo>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<int32> ===
export interface Cell<int32> {
}

export function loadCell<int32>(slice: Slice): Cell<int32> {
    return {
    };
}

export function storeCell<int32>(src: Cell<int32>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<address?> ===
export interface Cell<address?> {
}

export function loadCell<address?>(slice: Slice): Cell<address?> {
    return {
    };
}

export function storeCell<address?>(src: Cell<address?>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<int32 | int64> ===
export interface Cell<int32 | int64> {
}

export function loadCell<int32 | int64>(slice: Slice): Cell<int32 | int64> {
    return {
    };
}

export function storeCell<int32 | int64>(src: Cell<int32 | int64>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<int8> ===
export interface Cell<int8> {
}

export function loadCell<int8>(slice: Slice): Cell<int8> {
    return {
    };
}

export function storeCell<int8>(src: Cell<int8>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Cell<int8>> ===
export interface Cell<Cell<int8>> {
}

export function loadCell<Cell<int8>>(slice: Slice): Cell<Cell<int8>> {
    return {
    };
}

export function storeCell<Cell<int8>>(src: Cell<Cell<int8>>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<cell> ===
export interface Cell<cell> {
}

export function loadCell<cell>(slice: Slice): Cell<cell> {
    return {
    };
}

export function storeCell<cell>(src: Cell<cell>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Test5_1> ===
export interface Cell<Test5_1> {
}

export function loadCell<Test5_1>(slice: Slice): Cell<Test5_1> {
    return {
    };
}

export function storeCell<Test5_1>(src: Cell<Test5_1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<int16> ===
export interface Cell<int16> {
}

export function loadCell<int16>(slice: Slice): Cell<int16> {
    return {
    };
}

export function storeCell<int16>(src: Cell<int16>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<coins> ===
export interface Cell<coins> {
}

export function loadCell<coins>(slice: Slice): Cell<coins> {
    return {
    };
}

export function storeCell<coins>(src: Cell<coins>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<int10> ===
export interface Cell<int10> {
}

export function loadCell<int10>(slice: Slice): Cell<int10> {
    return {
    };
}

export function storeCell<int10>(src: Cell<int10>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Inner8_1> ===
export interface Cell<Inner8_1> {
}

export function loadCell<Inner8_1>(slice: Slice): Cell<Inner8_1> {
    return {
    };
}

export function storeCell<Inner8_1>(src: Cell<Inner8_1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Test11_1> ===
export interface Cell<Test11_1> {
}

export function loadCell<Test11_1>(slice: Slice): Cell<Test11_1> {
    return {
    };
}

export function storeCell<Test11_1>(src: Cell<Test11_1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Test11_2> ===
export interface Cell<Test11_2> {
}

export function loadCell<Test11_2>(slice: Slice): Cell<Test11_2> {
    return {
    };
}

export function storeCell<Test11_2>(src: Cell<Test11_2>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Test7_or> ===
export interface Cell<Test7_or> {
}

export function loadCell<Test7_or>(slice: Slice): Cell<Test7_or> {
    return {
    };
}

export function storeCell<Test7_or>(src: Cell<Test7_or>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

