
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell } from '@ton/core';

// === Test4_8 ===
export interface Test4_8 {
    a: number;
}

export function loadTest4_8(slice: Slice): Test4_8 {
    const a = slice.loadInt(8);
    return {
        a,
    };
}

export function storeTest4_8(src: Test4_8): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 8);
    };
}

// === Test4_16 ===
export interface Test4_16 {
    a: number;
}

export function loadTest4_16(slice: Slice): Test4_16 {
    const a = slice.loadInt(16);
    return {
        a,
    };
}

export function storeTest4_16(src: Test4_16): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 16);
    };
}

// === Test4_32 ===
export interface Test4_32 {
    a: number;
}

export function loadTest4_32(slice: Slice): Test4_32 {
    const a = slice.loadInt(32);
    return {
        a,
    };
}

export function storeTest4_32(src: Test4_32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 32);
    };
}

