
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell } from '@ton/core';

// === EFits2Bits ===
export enum EFits2Bits {
    ZERO = 0,
    ONE = 1,
    TWO = 2
}

// === EStartFrom1 ===
export enum EStartFrom1 {
    ONE = 1,
    TWO = 2,
    THREE = 3
}

// === EFillsAllUint3 ===
export enum EFillsAllUint3 {
    p0 = 0,
    p1 = 1,
    p2 = 2,
    p3 = 3,
    p4 = 4,
    p5 = 5,
    p6 = 6,
    p7 = 7
}

// === EStartFromM2 ===
export enum EStartFromM2 {
    M2 = -2,
    M1 = -1,
    ZERO = 0,
    P1 = 1,
    P2 = 2,
    P3 = 3
}

// === EFits8Bits ===
export enum EFits8Bits {
    E0 = 0,
    E110 = 110,
    E220 = 220
}

// === EMinMax ===
export enum EMinMax {
    MIN_INT = -115792089237316195423570985008687907853269984665640564039457584007913129639936,
    MAX_INT = 115792089237316195423570985008687907853269984665640564039457584007913129639935
}

// === E0Max ===
export enum E0Max {
    ZERO = 0,
    MAX_INT = 115792089237316195423570985008687907853269984665640564039457584007913129639935
}

// === Role ===
export enum Role {
    Admin = 0,
    User = 1
}

// === EncodedVari ===
export enum EncodedVari {
    ONE = 1,
    TWO = 2,
    MANY = 1267650600228229401496703205376
}

// === EOfCrc32 ===
export enum EOfCrc32 {
    hello = 907060870,
    world = 980881731
}

// === Amounts ===
export enum Amounts {
    zero = 0,
    nanoton = 1,
    small = 100000,
    more = 50000000,
    more1 = 50000001,
    one = 1000000000
}

// === WithEnumsUnion ===
export interface WithEnumsUnion {
    u: EFits8Bits | EStartFromM2;
}

export function loadWithEnumsUnion(slice: Slice): WithEnumsUnion {
    const u = /* union load - check opcodes */;
    return {
        u,
    };
}

export function storeWithEnumsUnion(src: WithEnumsUnion): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
    };
}

