/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress, Dictionary } from '@ton/core';

// === BounceMode ===
export enum BounceMode {
    NoBounce = 0,
    Only256BitsOfBody = 1,
    RichBounce = 2,
    RichBounceOnlyRootCell = 3
}

// === contract ===
export interface contract {
}

export function loadcontract(slice: Slice): contract {
    return {
    };
}

export function storecontract(src: contract): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === blockchain ===
export interface blockchain {
}

export function loadblockchain(slice: Slice): blockchain {
    return {
    };
}

export function storeblockchain(src: blockchain): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === PackOptions ===
export interface PackOptions {
    skipBitsNValidation: boolean;
}

export function loadPackOptions(slice: Slice): PackOptions {
    const skipBitsNValidation = slice.loadBoolean();
    return {
        skipBitsNValidation,
    };
}

export function storePackOptions(src: PackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.skipBitsNValidation);
    };
}

// === UnpackOptions ===
export interface UnpackOptions {
    assertEndAfterReading: boolean;
    throwIfOpcodeDoesNotMatch: bigint;
}

export function loadUnpackOptions(slice: Slice): UnpackOptions {
    const assertEndAfterReading = slice.loadBoolean();
    const throwIfOpcodeDoesNotMatch = slice.loadIntBig(257);
    return {
        assertEndAfterReading,
        throwIfOpcodeDoesNotMatch,
    };
}

export function storeUnpackOptions(src: UnpackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.assertEndAfterReading);
        builder.storeInt(src.throwIfOpcodeDoesNotMatch, 257);
    };
}

// === random ===
export interface random {
}

export function loadrandom(slice: Slice): random {
    return {
    };
}

export function storerandom(src: random): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === debug ===
export interface debug {
}

export function loaddebug(slice: Slice): debug {
    return {
    };
}

export function storedebug(src: debug): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === ContractState ===
export interface ContractState {
    code: Cell;
    data: Cell;
}

export function loadContractState(slice: Slice): ContractState {
    const code = slice.loadRef();
    const data = slice.loadRef();
    return {
        code,
        data,
    };
}

export function storeContractState(src: ContractState): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.code);
        builder.storeRef(src.data);
    };
}

// === AddressShardingOptions ===
export interface AddressShardingOptions {
    fixedPrefixLength: number;
    closeTo: Address;
}

export function loadAddressShardingOptions(slice: Slice): AddressShardingOptions {
    const fixedPrefixLength = slice.loadUint(5);
    const closeTo = slice.loadAddress();
    return {
        fixedPrefixLength,
        closeTo,
    };
}

export function storeAddressShardingOptions(src: AddressShardingOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.fixedPrefixLength, 5);
        builder.storeAddress(src.closeTo);
    };
}

// === AutoDeployAddress ===
export interface AutoDeployAddress {
    workchain: number;
    stateInit: ContractState | Cell;
    toShard: AddressShardingOptions | null;
}

export function loadAutoDeployAddress(slice: Slice): AutoDeployAddress {
    const workchain = slice.loadInt(8);
    const stateInit = /* union load - check opcodes */;
    const toShard = /* complex nullable: AddressShardingOptions | null */;
    return {
        workchain,
        stateInit,
        toShard,
    };
}

export function storeAutoDeployAddress(src: AutoDeployAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.workchain, 8);
        /* union store - switch on $$type */;
        /* complex nullable store */;
    };
}

// === ExtOutLogBucket ===
export const ExtOutLogBucketOpcode = 0x0;

export interface ExtOutLogBucket {
    readonly $$type: 'ExtOutLogBucket';
    topic: bigint | Buffer;
}

export function loadExtOutLogBucket(slice: Slice): ExtOutLogBucket {
    if (slice.loadUint(8) !== 0x0) {
        throw new Error('Invalid opcode for ExtOutLogBucket');
    }
    const topic = /* union load - check opcodes */;
    return {
        $$type: 'ExtOutLogBucket',
        topic,
    };
}

export function storeExtOutLogBucket(src: ExtOutLogBucket): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x0, 8);
        /* union store - switch on $$type */;
    };
}

// === OutMessage ===
export interface OutMessage {
    messageCell: Cell;
}

export function loadOutMessage(slice: Slice): OutMessage {
    const messageCell = slice.loadRef();
    return {
        messageCell,
    };
}

export function storeOutMessage(src: OutMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.messageCell);
    };
}

// === StateInit ===
export interface StateInit {
    fixedPrefixLength: number | null;
    special: unknown /* (bool, bool) */ | null;
    code: Cell | null;
    data: Cell | null;
    library: Cell | null;
}

export function loadStateInit(slice: Slice): StateInit {
    const fixedPrefixLength = slice.loadBit() ? slice.loadUint(5) : null;
    const special = /* complex nullable: unknown /* (bool, bool) */ | null */;
    const code = slice.loadMaybeRef();
    const data = slice.loadMaybeRef();
    const library = slice.loadMaybeRef();
    return {
        fixedPrefixLength,
        special,
        code,
        data,
        library,
    };
}

export function storeStateInit(src: StateInit): (builder: Builder) => void {
    return (builder: Builder) => {
        src.fixedPrefixLength !== null ? (builder.storeBit(true), builder.storeUint(src.fixedPrefixLength, 5)) : builder.storeBit(false);
        /* complex nullable store */;
        builder.storeMaybeRef(src.code);
        builder.storeMaybeRef(src.data);
        builder.storeMaybeRef(src.library);
    };
}

// === InMessage ===
export interface InMessage {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    body: Slice;
}

export function loadInMessage(slice: Slice): InMessage {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const body = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        body,
    };
}

export function storeInMessage(src: InMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.body);
    };
}

// === InMessageBounced ===
export interface InMessageBounced {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    bouncedBody: Slice;
}

export function loadInMessageBounced(slice: Slice): InMessageBounced {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const bouncedBody = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        bouncedBody,
    };
}

export function storeInMessageBounced(src: InMessageBounced): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.bouncedBody);
    };
}

// === RichBounceBody ===
export const RichBounceBodyOpcode = 0xfffffffe;

export interface RichBounceBody {
    readonly $$type: 'RichBounceBody';
    originalBody: Cell;
    originalInfo: Cell;
    bouncedByPhase: number;
    exitCode: number;
    computePhase: RichBounceComputePhaseInfo | null;
}

export function loadRichBounceBody(slice: Slice): RichBounceBody {
    if (slice.loadUint(32) !== 0xfffffffe) {
        throw new Error('Invalid opcode for RichBounceBody');
    }
    const originalBody = slice.loadRef();
    const originalInfo = slice.loadRef();
    const bouncedByPhase = slice.loadUint(8);
    const exitCode = slice.loadInt(32);
    const computePhase = /* complex nullable: RichBounceComputePhaseInfo | null */;
    return {
        $$type: 'RichBounceBody',
        originalBody,
        originalInfo,
        bouncedByPhase,
        exitCode,
        computePhase,
    };
}

export function storeRichBounceBody(src: RichBounceBody): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0xfffffffe, 32);
        builder.storeRef(src.originalBody);
        builder.storeRef(src.originalInfo);
        builder.storeUint(src.bouncedByPhase, 8);
        builder.storeInt(src.exitCode, 32);
        /* complex nullable store */;
    };
}

// === RichBounceComputePhaseInfo ===
export interface RichBounceComputePhaseInfo {
    gasUsed: number;
    vmSteps: number;
}

export function loadRichBounceComputePhaseInfo(slice: Slice): RichBounceComputePhaseInfo {
    const gasUsed = slice.loadUint(32);
    const vmSteps = slice.loadUint(32);
    return {
        gasUsed,
        vmSteps,
    };
}

export function storeRichBounceComputePhaseInfo(src: RichBounceComputePhaseInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.gasUsed, 32);
        builder.storeUint(src.vmSteps, 32);
    };
}

// === RichBounceOriginalMsgInfo ===
export interface RichBounceOriginalMsgInfo {
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    createdLt: bigint;
    createdAt: number;
}

export function loadRichBounceOriginalMsgInfo(slice: Slice): RichBounceOriginalMsgInfo {
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    return {
        valueCoins,
        valueExtra,
        createdLt,
        createdAt,
    };
}

export function storeRichBounceOriginalMsgInfo(src: RichBounceOriginalMsgInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
    };
}

// === MsgSinglePrefix32 ===
export const MsgSinglePrefix32Opcode = 0x87654321;

export interface MsgSinglePrefix32 {
    readonly $$type: 'MsgSinglePrefix32';
    amount1: bigint;
    amount2: bigint;
}

export function loadMsgSinglePrefix32(slice: Slice): MsgSinglePrefix32 {
    if (slice.loadUint(32) !== 0x87654321) {
        throw new Error('Invalid opcode for MsgSinglePrefix32');
    }
    const amount1 = slice.loadCoins();
    const amount2 = slice.loadCoins();
    return {
        $$type: 'MsgSinglePrefix32',
        amount1,
        amount2,
    };
}

export function storeMsgSinglePrefix32(src: MsgSinglePrefix32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x87654321, 32);
        builder.storeCoins(src.amount1);
        builder.storeCoins(src.amount2);
    };
}

// === MsgSinglePrefix48 ===
export const MsgSinglePrefix48Opcode = 0x876543211234;

export interface MsgSinglePrefix48 {
    readonly $$type: 'MsgSinglePrefix48';
    amount: bigint | bigint;
}

export function loadMsgSinglePrefix48(slice: Slice): MsgSinglePrefix48 {
    if (slice.loadUint(48) !== 0x876543211234) {
        throw new Error('Invalid opcode for MsgSinglePrefix48');
    }
    const amount = /* union load - check opcodes */;
    return {
        $$type: 'MsgSinglePrefix48',
        amount,
    };
}

export function storeMsgSinglePrefix48(src: MsgSinglePrefix48): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x876543211234, 48);
        /* union store - switch on $$type */;
    };
}

// === CounterIncrement ===
export const CounterIncrementOpcode = 0x12345678;

export interface CounterIncrement {
    readonly $$type: 'CounterIncrement';
    counter_id: number;
    inc_by: number;
}

export function loadCounterIncrement(slice: Slice): CounterIncrement {
    if (slice.loadUint(32) !== 0x12345678) {
        throw new Error('Invalid opcode for CounterIncrement');
    }
    const counter_id = slice.loadInt(8);
    const inc_by = slice.loadInt(32);
    return {
        $$type: 'CounterIncrement',
        counter_id,
        inc_by,
    };
}

export function storeCounterIncrement(src: CounterIncrement): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x12345678, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.inc_by, 32);
    };
}

// === CounterDecrement ===
export const CounterDecrementOpcode = 0x23456789;

export interface CounterDecrement {
    readonly $$type: 'CounterDecrement';
    counter_id: number;
    dec_by: number;
}

export function loadCounterDecrement(slice: Slice): CounterDecrement {
    if (slice.loadUint(32) !== 0x23456789) {
        throw new Error('Invalid opcode for CounterDecrement');
    }
    const counter_id = slice.loadInt(8);
    const dec_by = slice.loadInt(32);
    return {
        $$type: 'CounterDecrement',
        counter_id,
        dec_by,
    };
}

export function storeCounterDecrement(src: CounterDecrement): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x23456789, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.dec_by, 32);
    };
}

// === CounterReset0 ===
export const CounterReset0Opcode = 0x34567890;

export interface CounterReset0 {
    readonly $$type: 'CounterReset0';
    counter_id: number;
}

export function loadCounterReset0(slice: Slice): CounterReset0 {
    if (slice.loadUint(32) !== 0x34567890) {
        throw new Error('Invalid opcode for CounterReset0');
    }
    const counter_id = slice.loadInt(8);
    return {
        $$type: 'CounterReset0',
        counter_id,
    };
}

export function storeCounterReset0(src: CounterReset0): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x34567890, 32);
        builder.storeInt(src.counter_id, 8);
    };
}

// === CounterResetTo ===
export const CounterResetToOpcode = 0x184300;

export interface CounterResetTo {
    readonly $$type: 'CounterResetTo';
    counter_id: number;
    initial_value: bigint;
}

export function loadCounterResetTo(slice: Slice): CounterResetTo {
    if (slice.loadUint(32) !== 0x184300) {
        throw new Error('Invalid opcode for CounterResetTo');
    }
    const counter_id = slice.loadInt(8);
    const initial_value = slice.loadIntBig(64);
    return {
        $$type: 'CounterResetTo',
        counter_id,
        initial_value,
    };
}

export function storeCounterResetTo(src: CounterResetTo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x184300, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.initial_value, 64);
    };
}

// === BodyPayload1 ===
export const BodyPayload1Opcode = 0x1;

export interface BodyPayload1 {
    readonly $$type: 'BodyPayload1';
    should_forward: boolean;
    n_times: number;
    content: Slice;
}

export function loadBodyPayload1(slice: Slice): BodyPayload1 {
    if (slice.loadUint(3) !== 0x1) {
        throw new Error('Invalid opcode for BodyPayload1');
    }
    const should_forward = slice.loadBoolean();
    const n_times = slice.loadInt(32);
    const content = slice.clone();
    return {
        $$type: 'BodyPayload1',
        should_forward,
        n_times,
        content,
    };
}

export function storeBodyPayload1(src: BodyPayload1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 3);
        builder.storeBit(src.should_forward);
        builder.storeInt(src.n_times, 32);
        builder.storeSlice(src.content);
    };
}

// === BodyPayload2 ===
export const BodyPayload2Opcode = 0x1;

export interface BodyPayload2 {
    readonly $$type: 'BodyPayload2';
    master_id: number;
    owner_address: Address;
}

export function loadBodyPayload2(slice: Slice): BodyPayload2 {
    if (slice.loadUint(2) !== 0x1) {
        throw new Error('Invalid opcode for BodyPayload2');
    }
    const master_id = slice.loadInt(8);
    const owner_address = slice.loadAddress();
    return {
        $$type: 'BodyPayload2',
        master_id,
        owner_address,
    };
}

export function storeBodyPayload2(src: BodyPayload2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 2);
        builder.storeInt(src.master_id, 8);
        builder.storeAddress(src.owner_address);
    };
}

// === SayHiAndGoodbye ===
export const SayHiAndGoodbyeOpcode = 0x89;

export interface SayHiAndGoodbye {
    readonly $$type: 'SayHiAndGoodbye';
    dest_addr: Address | null;
    body: BodyPayload1 | BodyPayload2;
}

export function loadSayHiAndGoodbye(slice: Slice): SayHiAndGoodbye {
    if (slice.loadUint(8) !== 0x89) {
        throw new Error('Invalid opcode for SayHiAndGoodbye');
    }
    const dest_addr = slice.loadMaybeAddress();
    const body = /* union load - check opcodes */;
    return {
        $$type: 'SayHiAndGoodbye',
        dest_addr,
        body,
    };
}

export function storeSayHiAndGoodbye(src: SayHiAndGoodbye): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x89, 8);
        builder.storeAddress(src.dest_addr);
        /* union store - switch on $$type */;
    };
}

// === SayStoreInChain ===
export const SayStoreInChainOpcode = 0x13;

export interface SayStoreInChain {
    readonly $$type: 'SayStoreInChain';
    in_masterchain: boolean;
    contents: Cell;
}

export function loadSayStoreInChain(slice: Slice): SayStoreInChain {
    if (slice.loadUint(16) !== 0x13) {
        throw new Error('Invalid opcode for SayStoreInChain');
    }
    const in_masterchain = slice.loadBoolean();
    const contents = slice.loadRef();
    return {
        $$type: 'SayStoreInChain',
        in_masterchain,
        contents,
    };
}

export function storeSayStoreInChain(src: SayStoreInChain): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x13, 16);
        builder.storeBit(src.in_masterchain);
        builder.storeRef(src.contents);
    };
}

// === TransferParams1 ===
export const TransferParams1Opcode = 0x794;

export interface TransferParams1 {
    readonly $$type: 'TransferParams1';
    dest_int: Address;
    amount: bigint;
    dest_ext: Address | ExternalAddress | null;
}

export function loadTransferParams1(slice: Slice): TransferParams1 {
    if (slice.loadUint(12) !== 0x794) {
        throw new Error('Invalid opcode for TransferParams1');
    }
    const dest_int = slice.loadAddress();
    const amount = slice.loadCoins();
    const dest_ext = slice.loadAddressAny();
    return {
        $$type: 'TransferParams1',
        dest_int,
        amount,
        dest_ext,
    };
}

export function storeTransferParams1(src: TransferParams1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x794, 12);
        builder.storeAddress(src.dest_int);
        builder.storeCoins(src.amount);
        builder.storeAddress(src.dest_ext);
    };
}

// === TransferParams2 ===
export const TransferParams2Opcode = 0x9;

export interface TransferParams2 {
    readonly $$type: 'TransferParams2';
    intVector: unknown /* (int32, coins?, uint64) */;
    needs_more: Cell;
}

export function loadTransferParams2(slice: Slice): TransferParams2 {
    if (slice.loadUint(4) !== 0x9) {
        throw new Error('Invalid opcode for TransferParams2');
    }
    const intVector = /* unknown type */;
    const needs_more = slice.loadRef();
    return {
        $$type: 'TransferParams2',
        intVector,
        needs_more,
    };
}

export function storeTransferParams2(src: TransferParams2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x9, 4);
        /* unknown type */;
        builder.storeRef(src.needs_more);
    };
}

// === MsgTransfer ===
export const MsgTransferOpcode = 0xfb3701ff;

export interface MsgTransfer {
    readonly $$type: 'MsgTransfer';
    params: EitherLeft<TransferParams> | EitherRight<Cell<TransferParams>>;
}

export function loadMsgTransfer(slice: Slice): MsgTransfer {
    if (slice.loadUint(32) !== 0xfb3701ff) {
        throw new Error('Invalid opcode for MsgTransfer');
    }
    const params = /* union load - check opcodes */;
    return {
        $$type: 'MsgTransfer',
        params,
    };
}

export function storeMsgTransfer(src: MsgTransfer): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0xfb3701ff, 32);
        /* union store - switch on $$type */;
    };
}

// === MapLookupResult<slice> ===
export interface MapLookupResult<slice> {
    isFound: boolean;
}

export function loadMapLookupResult<slice>(slice: Slice): MapLookupResult<slice> {
    const isFound = slice.loadBoolean();
    return {
        isFound,
    };
}

export function storeMapLookupResult<slice>(src: MapLookupResult<slice>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.isFound);
    };
}

// === Cell<RichBounceOriginalMsgInfo> ===
export interface Cell<RichBounceOriginalMsgInfo> {
}

export function loadCell<RichBounceOriginalMsgInfo>(slice: Slice): Cell<RichBounceOriginalMsgInfo> {
    return {
    };
}

export function storeCell<RichBounceOriginalMsgInfo>(src: Cell<RichBounceOriginalMsgInfo>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<BodyPayload> ===
export interface Cell<BodyPayload> {
}

export function loadCell<BodyPayload>(slice: Slice): Cell<BodyPayload> {
    return {
    };
}

export function storeCell<BodyPayload>(src: Cell<BodyPayload>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<bool> ===
export interface Cell<bool> {
}

export function loadCell<bool>(slice: Slice): Cell<bool> {
    return {
    };
}

export function storeCell<bool>(src: Cell<bool>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<TransferParams> ===
export interface Cell<TransferParams> {
}

export function loadCell<TransferParams>(slice: Slice): Cell<TransferParams> {
    return {
    };
}

export function storeCell<TransferParams>(src: Cell<TransferParams>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === EitherLeft<TransferParams> ===
export interface EitherLeft<TransferParams> {
    value: TransferParams1 | TransferParams2;
}

export function loadEitherLeft<TransferParams>(slice: Slice): EitherLeft<TransferParams> {
    const value = /* union load - check opcodes */;
    return {
        value,
    };
}

export function storeEitherLeft<TransferParams>(src: EitherLeft<TransferParams>): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
    };
}

// === EitherRight<Cell<TransferParams>> ===
export interface EitherRight<Cell<TransferParams>> {
    value: Cell;
}

export function loadEitherRight<Cell<TransferParams>>(slice: Slice): EitherRight<Cell<TransferParams>> {
    const value = slice.loadRef();
    return {
        value,
    };
}

export function storeEitherRight<Cell<TransferParams>>(src: EitherRight<Cell<TransferParams>>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.value);
    };
}

// === Cell<MsgSinglePrefix32> ===
export interface Cell<MsgSinglePrefix32> {
}

export function loadCell<MsgSinglePrefix32>(slice: Slice): Cell<MsgSinglePrefix32> {
    return {
    };
}

export function storeCell<MsgSinglePrefix32>(src: Cell<MsgSinglePrefix32>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<MsgSinglePrefix48> ===
export interface Cell<MsgSinglePrefix48> {
}

export function loadCell<MsgSinglePrefix48>(slice: Slice): Cell<MsgSinglePrefix48> {
    return {
    };
}

export function storeCell<MsgSinglePrefix48>(src: Cell<MsgSinglePrefix48>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<MsgCounter1> ===
export interface Cell<MsgCounter1> {
}

export function loadCell<MsgCounter1>(slice: Slice): Cell<MsgCounter1> {
    return {
    };
}

export function storeCell<MsgCounter1>(src: Cell<MsgCounter1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<MsgExternal1> ===
export interface Cell<MsgExternal1> {
}

export function loadCell<MsgExternal1>(slice: Slice): Cell<MsgExternal1> {
    return {
    };
}

export function storeCell<MsgExternal1>(src: Cell<MsgExternal1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<BodyPayload1> ===
export interface Cell<BodyPayload1> {
}

export function loadCell<BodyPayload1>(slice: Slice): Cell<BodyPayload1> {
    return {
    };
}

export function storeCell<BodyPayload1>(src: Cell<BodyPayload1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<BodyPayload2> ===
export interface Cell<BodyPayload2> {
}

export function loadCell<BodyPayload2>(slice: Slice): Cell<BodyPayload2> {
    return {
    };
}

export function storeCell<BodyPayload2>(src: Cell<BodyPayload2>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<MsgTransfer> ===
export interface Cell<MsgTransfer> {
}

export function loadCell<MsgTransfer>(slice: Slice): Cell<MsgTransfer> {
    return {
    };
}

export function storeCell<MsgTransfer>(src: Cell<MsgTransfer>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<TransferParams1> ===
export interface Cell<TransferParams1> {
}

export function loadCell<TransferParams1>(slice: Slice): Cell<TransferParams1> {
    return {
    };
}

export function storeCell<TransferParams1>(src: Cell<TransferParams1>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<TransferParams2> ===
export interface Cell<TransferParams2> {
}

export function loadCell<TransferParams2>(slice: Slice): Cell<TransferParams2> {
    return {
    };
}

export function storeCell<TransferParams2>(src: Cell<TransferParams2>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

