/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress, Dictionary } from '@ton/core';

// === BounceMode ===
export enum BounceMode {
    NoBounce = 0,
    Only256BitsOfBody = 1,
    RichBounce = 2,
    RichBounceOnlyRootCell = 3
}

// === contract ===
export interface contract {
}

export function loadcontract(slice: Slice): contract {
    return {
    };
}

export function storecontract(src: contract): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === blockchain ===
export interface blockchain {
}

export function loadblockchain(slice: Slice): blockchain {
    return {
    };
}

export function storeblockchain(src: blockchain): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === PackOptions ===
export interface PackOptions {
    skipBitsNValidation: boolean;
}

export function loadPackOptions(slice: Slice): PackOptions {
    const skipBitsNValidation = slice.loadBoolean();
    return {
        skipBitsNValidation,
    };
}

export function storePackOptions(src: PackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.skipBitsNValidation);
    };
}

// === UnpackOptions ===
export interface UnpackOptions {
    assertEndAfterReading: boolean;
    throwIfOpcodeDoesNotMatch: bigint;
}

export function loadUnpackOptions(slice: Slice): UnpackOptions {
    const assertEndAfterReading = slice.loadBoolean();
    const throwIfOpcodeDoesNotMatch = slice.loadIntBig(257);
    return {
        assertEndAfterReading,
        throwIfOpcodeDoesNotMatch,
    };
}

export function storeUnpackOptions(src: UnpackOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.assertEndAfterReading);
        builder.storeInt(src.throwIfOpcodeDoesNotMatch, 257);
    };
}

// === random ===
export interface random {
}

export function loadrandom(slice: Slice): random {
    return {
    };
}

export function storerandom(src: random): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === debug ===
export interface debug {
}

export function loaddebug(slice: Slice): debug {
    return {
    };
}

export function storedebug(src: debug): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === ContractState ===
export interface ContractState {
    code: Cell;
    data: Cell;
}

export function loadContractState(slice: Slice): ContractState {
    const code = slice.loadRef();
    const data = slice.loadRef();
    return {
        code,
        data,
    };
}

export function storeContractState(src: ContractState): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.code);
        builder.storeRef(src.data);
    };
}

// === AddressShardingOptions ===
export interface AddressShardingOptions {
    fixedPrefixLength: number;
    closeTo: Address;
}

export function loadAddressShardingOptions(slice: Slice): AddressShardingOptions {
    const fixedPrefixLength = slice.loadUint(5);
    const closeTo = slice.loadAddress();
    return {
        fixedPrefixLength,
        closeTo,
    };
}

export function storeAddressShardingOptions(src: AddressShardingOptions): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.fixedPrefixLength, 5);
        builder.storeAddress(src.closeTo);
    };
}

// === AutoDeployAddress ===
export interface AutoDeployAddress {
    workchain: number;
    stateInit: ContractState | Cell;
    toShard: AddressShardingOptions | null;
}

export function loadAutoDeployAddress(slice: Slice): AutoDeployAddress {
    const workchain = slice.loadInt(8);
    const stateInit = /* union load - check opcodes */;
    const toShard = /* complex nullable: AddressShardingOptions | null */;
    return {
        workchain,
        stateInit,
        toShard,
    };
}

export function storeAutoDeployAddress(src: AutoDeployAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.workchain, 8);
        /* union store - switch on $$type */;
        /* complex nullable store */;
    };
}

// === ExtOutLogBucket ===
export const ExtOutLogBucketOpcode = 0x0;

export interface ExtOutLogBucket {
    readonly $$type: 'ExtOutLogBucket';
    topic: bigint | Buffer;
}

export function loadExtOutLogBucket(slice: Slice): ExtOutLogBucket {
    if (slice.loadUint(8) !== 0x0) {
        throw new Error('Invalid opcode for ExtOutLogBucket');
    }
    const topic = /* union load - check opcodes */;
    return {
        $$type: 'ExtOutLogBucket',
        topic,
    };
}

export function storeExtOutLogBucket(src: ExtOutLogBucket): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x0, 8);
        /* union store - switch on $$type */;
    };
}

// === OutMessage ===
export interface OutMessage {
    messageCell: Cell;
}

export function loadOutMessage(slice: Slice): OutMessage {
    const messageCell = slice.loadRef();
    return {
        messageCell,
    };
}

export function storeOutMessage(src: OutMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.messageCell);
    };
}

// === StateInit ===
export interface StateInit {
    fixedPrefixLength: number | null;
    special: unknown /* (bool, bool) */ | null;
    code: Cell | null;
    data: Cell | null;
    library: Cell | null;
}

export function loadStateInit(slice: Slice): StateInit {
    const fixedPrefixLength = slice.loadBit() ? slice.loadUint(5) : null;
    const special = /* complex nullable: unknown /* (bool, bool) */ | null */;
    const code = slice.loadMaybeRef();
    const data = slice.loadMaybeRef();
    const library = slice.loadMaybeRef();
    return {
        fixedPrefixLength,
        special,
        code,
        data,
        library,
    };
}

export function storeStateInit(src: StateInit): (builder: Builder) => void {
    return (builder: Builder) => {
        src.fixedPrefixLength !== null ? (builder.storeBit(true), builder.storeUint(src.fixedPrefixLength, 5)) : builder.storeBit(false);
        /* complex nullable store */;
        builder.storeMaybeRef(src.code);
        builder.storeMaybeRef(src.data);
        builder.storeMaybeRef(src.library);
    };
}

// === InMessage ===
export interface InMessage {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    body: Slice;
}

export function loadInMessage(slice: Slice): InMessage {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const body = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        body,
    };
}

export function storeInMessage(src: InMessage): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.body);
    };
}

// === InMessageBounced ===
export interface InMessageBounced {
    senderAddress: Address;
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    originalForwardFee: bigint;
    createdLt: bigint;
    createdAt: number;
    bouncedBody: Slice;
}

export function loadInMessageBounced(slice: Slice): InMessageBounced {
    const senderAddress = slice.loadAddress();
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const originalForwardFee = slice.loadCoins();
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    const bouncedBody = slice.clone();
    return {
        senderAddress,
        valueCoins,
        valueExtra,
        originalForwardFee,
        createdLt,
        createdAt,
        bouncedBody,
    };
}

export function storeInMessageBounced(src: InMessageBounced): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.senderAddress);
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeCoins(src.originalForwardFee);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
        builder.storeSlice(src.bouncedBody);
    };
}

// === RichBounceBody ===
export const RichBounceBodyOpcode = 0xfffffffe;

export interface RichBounceBody {
    readonly $$type: 'RichBounceBody';
    originalBody: Cell;
    originalInfo: Cell;
    bouncedByPhase: number;
    exitCode: number;
    computePhase: RichBounceComputePhaseInfo | null;
}

export function loadRichBounceBody(slice: Slice): RichBounceBody {
    if (slice.loadUint(32) !== 0xfffffffe) {
        throw new Error('Invalid opcode for RichBounceBody');
    }
    const originalBody = slice.loadRef();
    const originalInfo = slice.loadRef();
    const bouncedByPhase = slice.loadUint(8);
    const exitCode = slice.loadInt(32);
    const computePhase = /* complex nullable: RichBounceComputePhaseInfo | null */;
    return {
        $$type: 'RichBounceBody',
        originalBody,
        originalInfo,
        bouncedByPhase,
        exitCode,
        computePhase,
    };
}

export function storeRichBounceBody(src: RichBounceBody): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0xfffffffe, 32);
        builder.storeRef(src.originalBody);
        builder.storeRef(src.originalInfo);
        builder.storeUint(src.bouncedByPhase, 8);
        builder.storeInt(src.exitCode, 32);
        /* complex nullable store */;
    };
}

// === RichBounceComputePhaseInfo ===
export interface RichBounceComputePhaseInfo {
    gasUsed: number;
    vmSteps: number;
}

export function loadRichBounceComputePhaseInfo(slice: Slice): RichBounceComputePhaseInfo {
    const gasUsed = slice.loadUint(32);
    const vmSteps = slice.loadUint(32);
    return {
        gasUsed,
        vmSteps,
    };
}

export function storeRichBounceComputePhaseInfo(src: RichBounceComputePhaseInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.gasUsed, 32);
        builder.storeUint(src.vmSteps, 32);
    };
}

// === RichBounceOriginalMsgInfo ===
export interface RichBounceOriginalMsgInfo {
    valueCoins: bigint;
    valueExtra: Dictionary<number, bigint>;
    createdLt: bigint;
    createdAt: number;
}

export function loadRichBounceOriginalMsgInfo(slice: Slice): RichBounceOriginalMsgInfo {
    const valueCoins = slice.loadCoins();
    const valueExtra = Dictionary.load(/* key dict, value dict */);
    const createdLt = slice.loadUintBig(64);
    const createdAt = slice.loadUint(32);
    return {
        valueCoins,
        valueExtra,
        createdLt,
        createdAt,
    };
}

export function storeRichBounceOriginalMsgInfo(src: RichBounceOriginalMsgInfo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeCoins(src.valueCoins);
        src.valueExtra.store(builder);
        builder.storeUint(src.createdLt, 64);
        builder.storeUint(src.createdAt, 32);
    };
}

// === JustInt32 ===
export interface JustInt32 {
    value: number;
}

export function loadJustInt32(slice: Slice): JustInt32 {
    const value = slice.loadInt(32);
    return {
        value,
    };
}

export function storeJustInt32(src: JustInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 32);
    };
}

// === Point ===
export interface Point {
    x: number;
    y: number;
}

export function loadPoint(slice: Slice): Point {
    const x = slice.loadInt(32);
    const y = slice.loadInt(32);
    return {
        x,
        y,
    };
}

export function storePoint(src: Point): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.x, 32);
        builder.storeInt(src.y, 32);
    };
}

// === TwoU ===
export interface TwoU {
    a: number;
    b: number;
}

export function loadTwoU(slice: Slice): TwoU {
    const a = slice.loadUint(8);
    const b = slice.loadUint(8);
    return {
        a,
        b,
    };
}

export function storeTwoU(src: TwoU): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.a, 8);
        builder.storeUint(src.b, 8);
    };
}

// === MapLookupResult<slice> ===
export interface MapLookupResult<slice> {
    isFound: boolean;
}

export function loadMapLookupResult<slice>(slice: Slice): MapLookupResult<slice> {
    const isFound = slice.loadBoolean();
    return {
        isFound,
    };
}

export function storeMapLookupResult<slice>(src: MapLookupResult<slice>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBit(src.isFound);
    };
}

// === Cell<RichBounceOriginalMsgInfo> ===
export interface Cell<RichBounceOriginalMsgInfo> {
}

export function loadCell<RichBounceOriginalMsgInfo>(slice: Slice): Cell<RichBounceOriginalMsgInfo> {
    return {
    };
}

export function storeCell<RichBounceOriginalMsgInfo>(src: Cell<RichBounceOriginalMsgInfo>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<JustInt32> ===
export interface Cell<JustInt32> {
}

export function loadCell<JustInt32>(slice: Slice): Cell<JustInt32> {
    return {
    };
}

export function storeCell<JustInt32>(src: Cell<JustInt32>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Point> ===
export interface Cell<Point> {
}

export function loadCell<Point>(slice: Slice): Cell<Point> {
    return {
    };
}

export function storeCell<Point>(src: Cell<Point>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<Point?> ===
export interface Cell<Point?> {
}

export function loadCell<Point?>(slice: Slice): Cell<Point?> {
    return {
    };
}

export function storeCell<Point?>(src: Cell<Point?>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === Cell<TwoU> ===
export interface Cell<TwoU> {
}

export function loadCell<TwoU>(slice: Slice): Cell<TwoU> {
    return {
    };
}

export function storeCell<TwoU>(src: Cell<TwoU>): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

