if (ANDROID AND NOT DEFINED TON_ANDROID_THIRD_PARTY_DIR)
  if (DEFINED ENV{ANDROID_NDK_ROOT})
    set(TON_ANDROID_NDK_ROOT "$ENV{ANDROID_NDK_ROOT}")
  elseif (ANDROID_NDK)
    set(TON_ANDROID_NDK_ROOT "${ANDROID_NDK}")
  elseif (CMAKE_ANDROID_NDK)
    set(TON_ANDROID_NDK_ROOT "${CMAKE_ANDROID_NDK}")
  else()
    message(FATAL_ERROR "ANDROID_NDK_ROOT is not set (and ANDROID_NDK/CMAKE_ANDROID_NDK not provided).")
  endif()

  if (DEFINED ANDROID_ABI)
    set(TON_ANDROID_ABI "${ANDROID_ABI}")
  elseif (DEFINED CMAKE_ANDROID_ARCH_ABI)
    set(TON_ANDROID_ABI "${CMAKE_ANDROID_ARCH_ABI}")
  else()
    message(FATAL_ERROR "ANDROID_ABI is not set; pass -DANDROID_ABI or use Android toolchain.")
  endif()

  set(TON_ANDROID_THIRD_PARTY_DIR "${CMAKE_CURRENT_BINARY_DIR}/android/third_party")

  if (TON_ANDROID_ABI STREQUAL "armeabi-v7a")
    set(TON_ANDROID_ARCH "arm")
    set(TON_ANDROID_ARCH_DIR "armv7")
    set(TON_ANDROID_SODIUM_DIR "libsodium-android-armv7-a")
    set(TON_ANDROID_OPENSSL_DIR "arm")
    set(TON_ANDROID_HOST "arm-linux-androideabi")
    set(TON_ANDROID_CLANG_PREFIX "armv7a-linux-androideabi")
  elseif (TON_ANDROID_ABI STREQUAL "arm64-v8a")
    set(TON_ANDROID_ARCH "arm64")
    set(TON_ANDROID_ARCH_DIR "armv8")
    set(TON_ANDROID_SODIUM_DIR "libsodium-android-armv8-a")
    set(TON_ANDROID_OPENSSL_DIR "arm64")
    set(TON_ANDROID_HOST "aarch64-linux-android")
    set(TON_ANDROID_CLANG_PREFIX "aarch64-linux-android")
  elseif (TON_ANDROID_ABI STREQUAL "x86")
    set(TON_ANDROID_ARCH "x86")
    set(TON_ANDROID_ARCH_DIR "i686")
    set(TON_ANDROID_SODIUM_DIR "libsodium-android-i686")
    set(TON_ANDROID_OPENSSL_DIR "x86")
    set(TON_ANDROID_HOST "i686-linux-android")
    set(TON_ANDROID_CLANG_PREFIX "i686-linux-android")
  elseif (TON_ANDROID_ABI STREQUAL "x86_64")
    set(TON_ANDROID_ARCH "x86_64")
    set(TON_ANDROID_ARCH_DIR "x86-64")
    set(TON_ANDROID_SODIUM_DIR "libsodium-android-westmere")
    set(TON_ANDROID_OPENSSL_DIR "x86_64")
    set(TON_ANDROID_HOST "x86_64-linux-android")
    set(TON_ANDROID_CLANG_PREFIX "x86_64-linux-android")
  else()
    message(FATAL_ERROR "Unsupported ANDROID_ABI: ${TON_ANDROID_ABI}")
  endif()

  if (CMAKE_ANDROID_API)
    set(TON_ANDROID_API "${CMAKE_ANDROID_API}")
  elseif (ANDROID_PLATFORM)
    string(REGEX REPLACE "android-" "" TON_ANDROID_API "${ANDROID_PLATFORM}")
  elseif (ANDROID_NATIVE_API_LEVEL)
    set(TON_ANDROID_API "${ANDROID_NATIVE_API_LEVEL}")
  else()
    set(TON_ANDROID_API "21")
  endif()

  set(TON_ANDROID_NDK_PREBUILT_DIR "${TON_ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt")
  set(TON_ANDROID_NDK_BIN "")
  set(TON_ANDROID_HOST_TAG "")
  set(_ton_host_arch "")
  if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
    set(_ton_host_arch "arm64")
  elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64)$")
    set(_ton_host_arch "x86_64")
  elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^i.86$")
    set(_ton_host_arch "x86")
  endif()

  set(_ton_host_tag_candidates "")
  if (WIN32)
    list(APPEND _ton_host_tag_candidates "windows-x86_64" "windows")
  elseif (APPLE)
    if (_ton_host_arch STREQUAL "arm64")
      list(APPEND _ton_host_tag_candidates "darwin-arm64" "darwin-x86_64")
    else()
      list(APPEND _ton_host_tag_candidates "darwin-x86_64" "darwin-arm64")
    endif()
  else()
    if (_ton_host_arch STREQUAL "arm64")
      list(APPEND _ton_host_tag_candidates "linux-arm64" "linux-aarch64" "linux-x86_64")
    else()
      list(APPEND _ton_host_tag_candidates "linux-x86_64")
    endif()
  endif()

  foreach(_ton_host_tag IN LISTS _ton_host_tag_candidates)
    if (EXISTS "${TON_ANDROID_NDK_PREBUILT_DIR}/${_ton_host_tag}/bin")
      set(TON_ANDROID_NDK_BIN "${TON_ANDROID_NDK_PREBUILT_DIR}/${_ton_host_tag}/bin")
      set(TON_ANDROID_HOST_TAG "${_ton_host_tag}")
      break()
    endif()
  endforeach()

  if (TON_ANDROID_NDK_BIN STREQUAL "")
    file(GLOB _ton_ndk_bins "${TON_ANDROID_NDK_PREBUILT_DIR}/*/bin")
    list(LENGTH _ton_ndk_bins _ton_ndk_bins_len)
    if (_ton_ndk_bins_len GREATER 0)
      list(GET _ton_ndk_bins 0 TON_ANDROID_NDK_BIN)
      get_filename_component(_ton_host_tag_dir "${TON_ANDROID_NDK_BIN}" DIRECTORY)
      get_filename_component(TON_ANDROID_HOST_TAG "${_ton_host_tag_dir}" NAME)
    endif()
  endif()

  if (TON_ANDROID_NDK_BIN STREQUAL "")
    message(FATAL_ERROR "Android NDK bin path not found under ${TON_ANDROID_NDK_PREBUILT_DIR}.")
  endif()

  set(TON_ANDROID_CC "${TON_ANDROID_NDK_BIN}/${TON_ANDROID_CLANG_PREFIX}${TON_ANDROID_API}-clang")
  if (NOT EXISTS "${TON_ANDROID_CC}")
    file(GLOB TON_ANDROID_CLANG_CANDIDATES
      "${TON_ANDROID_NDK_BIN}/${TON_ANDROID_CLANG_PREFIX}[0-9]*-clang")
    set(TON_ANDROID_CLANG_MAX "")
    foreach(TON_ANDROID_CLANG_CANDIDATE IN LISTS TON_ANDROID_CLANG_CANDIDATES)
      get_filename_component(TON_ANDROID_CLANG_FILE "${TON_ANDROID_CLANG_CANDIDATE}" NAME)
      string(REGEX REPLACE "^${TON_ANDROID_CLANG_PREFIX}([0-9]+)-clang$" "\\1"
        TON_ANDROID_CLANG_VER "${TON_ANDROID_CLANG_FILE}")
      if (TON_ANDROID_CLANG_VER MATCHES "^[0-9]+$")
        if (TON_ANDROID_CLANG_MAX STREQUAL "" OR TON_ANDROID_CLANG_VER GREATER TON_ANDROID_CLANG_MAX)
          set(TON_ANDROID_CLANG_MAX "${TON_ANDROID_CLANG_VER}")
        endif()
      endif()
    endforeach()
    if (TON_ANDROID_CLANG_MAX STREQUAL "")
      message(FATAL_ERROR "No NDK clang found for ${TON_ANDROID_CLANG_PREFIX} under ${TON_ANDROID_NDK_BIN}.")
    endif()
    message(STATUS "Requested Android API ${TON_ANDROID_API} not available for ${TON_ANDROID_ABI}; falling back to ${TON_ANDROID_CLANG_MAX}.")
    set(TON_ANDROID_API "${TON_ANDROID_CLANG_MAX}")
    set(TON_ANDROID_CC "${TON_ANDROID_NDK_BIN}/${TON_ANDROID_CLANG_PREFIX}${TON_ANDROID_API}-clang")
  endif()

  set(TON_ANDROID_CC "${TON_ANDROID_NDK_BIN}/${TON_ANDROID_CLANG_PREFIX}${TON_ANDROID_API}-clang")
  set(TON_ANDROID_CXX "${TON_ANDROID_NDK_BIN}/${TON_ANDROID_CLANG_PREFIX}${TON_ANDROID_API}-clang++")
  set(TON_ANDROID_AR "${TON_ANDROID_NDK_BIN}/llvm-ar")
  set(TON_ANDROID_RANLIB "${TON_ANDROID_NDK_BIN}/llvm-ranlib")
  set(TON_ANDROID_NM "${TON_ANDROID_NDK_BIN}/llvm-nm")

  message(STATUS "Android third_party dir: ${TON_ANDROID_THIRD_PARTY_DIR} (ABI=${TON_ANDROID_ABI}, API=${TON_ANDROID_API})")
endif()
