if(NOT DEFINED CRC32C_CMAKE_FILE)
  message(FATAL_ERROR "CRC32C_CMAKE_FILE must be defined")
endif()

if(NOT EXISTS "${CRC32C_CMAKE_FILE}")
  message(FATAL_ERROR "CRC32C CMakeLists.txt not found: ${CRC32C_CMAKE_FILE}")
endif()

file(READ "${CRC32C_CMAKE_FILE}" CRC32C_CMAKE_CONTENTS)

if(CRC32C_CMAKE_CONTENTS MATCHES "CMAKE_CXX_SIMULATE_ID STREQUAL \"MSVC\"")
  message(STATUS "CRC32C clang-cl/MSVC simulation patch already applied")
  return()
endif()

string(REPLACE
  "if(CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\")"
  "if(CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\" OR CMAKE_CXX_SIMULATE_ID STREQUAL \"MSVC\")"
  CRC32C_CMAKE_CONTENTS_UPDATED
  "${CRC32C_CMAKE_CONTENTS}"
)

string(REPLACE
  "endif(CMAKE_CXX_COMPILER_ID STREQUAL \"MSVC\")"
  "endif()"
  CRC32C_CMAKE_CONTENTS_UPDATED
  "${CRC32C_CMAKE_CONTENTS_UPDATED}"
)

if(CRC32C_CMAKE_CONTENTS STREQUAL CRC32C_CMAKE_CONTENTS_UPDATED)
  message(FATAL_ERROR "Failed to patch clang-cl/MSVC simulation condition in ${CRC32C_CMAKE_FILE}")
endif()

file(WRITE "${CRC32C_CMAKE_FILE}" "${CRC32C_CMAKE_CONTENTS_UPDATED}")
message(STATUS "Patched CRC32C for clang-cl MSVC frontend compatibility")
