
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell } from '@ton/core';

// === CounterIncrement ===
export const CounterIncrementOpcode = 0x1;

export interface CounterIncrement {
    readonly $$type: 'CounterIncrement';
    byValue: number;
}

export function loadCounterIncrement(slice: Slice): CounterIncrement {
    if (slice.loadUint(8) !== 0x1) {
        throw new Error('Invalid opcode for CounterIncrement');
    }
    const byValue = slice.loadInt(8);
    return {
        $$type: 'CounterIncrement',
        byValue,
    };
}

export function storeCounterIncrement(src: CounterIncrement): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 8);
        builder.storeInt(src.byValue, 8);
    };
}

// === CounterDecrementBy1 ===
export const CounterDecrementBy1Opcode = 0x3;

export interface CounterDecrementBy1 {
    readonly $$type: 'CounterDecrementBy1';
}

export function loadCounterDecrementBy1(slice: Slice): CounterDecrementBy1 {
    if (slice.loadUint(8) !== 0x3) {
        throw new Error('Invalid opcode for CounterDecrementBy1');
    }
    return {
        $$type: 'CounterDecrementBy1',
    };
}

export function storeCounterDecrementBy1(src: CounterDecrementBy1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x3, 8);
    };
}

// === SomeBytesFields ===
export interface SomeBytesFields {
    f1: Buffer;
}

export function loadSomeBytesFields(slice: Slice): SomeBytesFields {
    const f1 = slice.loadBuffer(1);
    return {
        f1,
    };
}

export function storeSomeBytesFields(src: SomeBytesFields): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBuffer(src.f1);
    };
}

