
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell } from '@ton/core';

// === Color ===
export enum Color {
    Red = 0,
    Green = 1,
    Blue = 2
}

// === StorWithStr ===
export interface StorWithStr {
    a: number;
    str: Slice;
    b: number;
}

export function loadStorWithStr(slice: Slice): StorWithStr {
    const a = slice.loadInt(32);
    const str = /* Note: uses custom serialization (TelegramString.unpackFromSlice) */ slice.clone();
    const b = slice.loadInt(32);
    return {
        a,
        str,
        b,
    };
}

export function storeStorWithStr(src: StorWithStr): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 32);
        /* Note: uses custom serialization (TelegramString.packToBuilder) */ builder.storeSlice(src.str);
        builder.storeInt(src.b, 32);
    };
}

// === PointWithCustomInt ===
export interface PointWithCustomInt {
    a: bigint;
    b: number;
}

export function loadPointWithCustomInt(slice: Slice): PointWithCustomInt {
    const a = /* Note: uses custom serialization (Custom8.unpackFromSlice) */ slice.loadIntBig(257);
    const b = slice.loadInt(8);
    return {
        a,
        b,
    };
}

export function storePointWithCustomInt(src: PointWithCustomInt): (builder: Builder) => void {
    return (builder: Builder) => {
        /* Note: uses custom serialization (Custom8.packToBuilder) */ builder.storeInt(src.a, 257);
        builder.storeInt(src.b, 8);
    };
}

// === WithMyBorder ===
export interface WithMyBorder {
    a: number;
    b: bigint;
}

export function loadWithMyBorder(slice: Slice): WithMyBorder {
    const a = slice.loadInt(8);
    const b = /* Note: uses custom serialization (MyBorderedInt.unpackFromSlice) */ slice.loadIntBig(257);
    return {
        a,
        b,
    };
}

export function storeWithMyBorder(src: WithMyBorder): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 8);
        /* Note: uses custom serialization (MyBorderedInt.packToBuilder) */ builder.storeInt(src.b, 257);
    };
}

// === WithFakeWriter ===
export interface WithFakeWriter {
    a: number;
    fake: [];
    b: number;
}

export function loadWithFakeWriter(slice: Slice): WithFakeWriter {
    const a = slice.loadInt(8);
    const fake = [];
    const b = slice.loadInt(8);
    return {
        a,
        fake,
        b,
    };
}

export function storeWithFakeWriter(src: WithFakeWriter): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 8);
        /* Note: uses custom serialization (MyCustomNothing.packToBuilder) */ (() => { const t = src.fake; })();
        builder.storeInt(src.b, 8);
    };
}

// === WithGlobalModifier ===
export interface WithGlobalModifier {
    a: number;
    g: [];
    n: number;
}

export function loadWithGlobalModifier(slice: Slice): WithGlobalModifier {
    const a = slice.loadInt(8);
    const g = /* Note: uses custom serialization (MagicGlobalModifier.unpackFromSlice) */ [];
    const n = slice.loadInt(8);
    return {
        a,
        g,
        n,
    };
}

export function storeWithGlobalModifier(src: WithGlobalModifier): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 8);
        /* Note: uses custom serialization (MagicGlobalModifier.packToBuilder) */ (() => { const t = src.g; })();
        builder.storeInt(src.n, 8);
    };
}

// === HasOnlyWithUnpack ===
export interface HasOnlyWithUnpack {
    wu: number;
}

export function loadHasOnlyWithUnpack(slice: Slice): HasOnlyWithUnpack {
    const wu = /* Note: uses custom serialization (OnlyWithUnpack.unpackFromSlice) */ slice.loadInt(8);
    return {
        wu,
    };
}

export function storeHasOnlyWithUnpack(src: HasOnlyWithUnpack): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.wu, 8);
    };
}

