
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress } from '@ton/core';

// === MsgSinglePrefix32 ===
export const MsgSinglePrefix32Opcode = 0x87654321;

export interface MsgSinglePrefix32 {
    readonly $$type: 'MsgSinglePrefix32';
    amount1: bigint;
    amount2: bigint;
}

export function loadMsgSinglePrefix32(slice: Slice): MsgSinglePrefix32 {
    if (slice.loadUint(32) !== 0x87654321) {
        throw new Error('Invalid opcode for MsgSinglePrefix32');
    }
    const amount1 = slice.loadCoins();
    const amount2 = slice.loadCoins();
    return {
        $$type: 'MsgSinglePrefix32',
        amount1,
        amount2,
    };
}

export function storeMsgSinglePrefix32(src: MsgSinglePrefix32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x87654321, 32);
        builder.storeCoins(src.amount1);
        builder.storeCoins(src.amount2);
    };
}

// === MsgSinglePrefix48 ===
export const MsgSinglePrefix48Opcode = 0x876543211234;

export interface MsgSinglePrefix48 {
    readonly $$type: 'MsgSinglePrefix48';
    amount: bigint | bigint;
}

export function loadMsgSinglePrefix48(slice: Slice): MsgSinglePrefix48 {
    if (slice.loadUint(48) !== 0x876543211234) {
        throw new Error('Invalid opcode for MsgSinglePrefix48');
    }
    const amount = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return slice.loadCoins();
        if (tag === 1) return slice.loadUintBig(64);
        throw new Error('Unknown union tag');
    })();
    return {
        $$type: 'MsgSinglePrefix48',
        amount,
    };
}

export function storeMsgSinglePrefix48(src: MsgSinglePrefix48): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x876543211234, 48);
        (() => {
            if (typeof src.amount === 'bigint' || typeof src.amount === 'number') { builder.storeUint(0, 1); builder.storeCoins(src.amount); }
            else if (typeof src.amount === 'bigint' || typeof src.amount === 'number') { builder.storeUint(1, 1); builder.storeUint(src.amount, 64); }
            else throw new Error('Unknown union variant');
        })();
    };
}

// === CounterIncrement ===
export const CounterIncrementOpcode = 0x12345678;

export interface CounterIncrement {
    readonly $$type: 'CounterIncrement';
    counter_id: number;
    inc_by: number;
}

export function loadCounterIncrement(slice: Slice): CounterIncrement {
    if (slice.loadUint(32) !== 0x12345678) {
        throw new Error('Invalid opcode for CounterIncrement');
    }
    const counter_id = slice.loadInt(8);
    const inc_by = slice.loadInt(32);
    return {
        $$type: 'CounterIncrement',
        counter_id,
        inc_by,
    };
}

export function storeCounterIncrement(src: CounterIncrement): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x12345678, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.inc_by, 32);
    };
}

// === CounterDecrement ===
export const CounterDecrementOpcode = 0x23456789;

export interface CounterDecrement {
    readonly $$type: 'CounterDecrement';
    counter_id: number;
    dec_by: number;
}

export function loadCounterDecrement(slice: Slice): CounterDecrement {
    if (slice.loadUint(32) !== 0x23456789) {
        throw new Error('Invalid opcode for CounterDecrement');
    }
    const counter_id = slice.loadInt(8);
    const dec_by = slice.loadInt(32);
    return {
        $$type: 'CounterDecrement',
        counter_id,
        dec_by,
    };
}

export function storeCounterDecrement(src: CounterDecrement): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x23456789, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.dec_by, 32);
    };
}

// === CounterReset0 ===
export const CounterReset0Opcode = 0x34567890;

export interface CounterReset0 {
    readonly $$type: 'CounterReset0';
    counter_id: number;
}

export function loadCounterReset0(slice: Slice): CounterReset0 {
    if (slice.loadUint(32) !== 0x34567890) {
        throw new Error('Invalid opcode for CounterReset0');
    }
    const counter_id = slice.loadInt(8);
    return {
        $$type: 'CounterReset0',
        counter_id,
    };
}

export function storeCounterReset0(src: CounterReset0): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x34567890, 32);
        builder.storeInt(src.counter_id, 8);
    };
}

// === CounterResetTo ===
export const CounterResetToOpcode = 0x184300;

export interface CounterResetTo {
    readonly $$type: 'CounterResetTo';
    counter_id: number;
    initial_value: bigint;
}

export function loadCounterResetTo(slice: Slice): CounterResetTo {
    if (slice.loadUint(32) !== 0x184300) {
        throw new Error('Invalid opcode for CounterResetTo');
    }
    const counter_id = slice.loadInt(8);
    const initial_value = slice.loadIntBig(64);
    return {
        $$type: 'CounterResetTo',
        counter_id,
        initial_value,
    };
}

export function storeCounterResetTo(src: CounterResetTo): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x184300, 32);
        builder.storeInt(src.counter_id, 8);
        builder.storeInt(src.initial_value, 64);
    };
}

// === BodyPayload1 ===
export const BodyPayload1Opcode = 0x1;

export interface BodyPayload1 {
    readonly $$type: 'BodyPayload1';
    should_forward: boolean;
    n_times: number;
    content: Slice;
}

export function loadBodyPayload1(slice: Slice): BodyPayload1 {
    if (slice.loadUint(3) !== 0x1) {
        throw new Error('Invalid opcode for BodyPayload1');
    }
    const should_forward = slice.loadBoolean();
    const n_times = slice.loadInt(32);
    const content = slice.clone();
    return {
        $$type: 'BodyPayload1',
        should_forward,
        n_times,
        content,
    };
}

export function storeBodyPayload1(src: BodyPayload1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 3);
        builder.storeBit(src.should_forward);
        builder.storeInt(src.n_times, 32);
        builder.storeSlice(src.content);
    };
}

// === BodyPayload2 ===
export const BodyPayload2Opcode = 0x1;

export interface BodyPayload2 {
    readonly $$type: 'BodyPayload2';
    master_id: number;
    owner_address: Address;
}

export function loadBodyPayload2(slice: Slice): BodyPayload2 {
    if (slice.loadUint(2) !== 0x1) {
        throw new Error('Invalid opcode for BodyPayload2');
    }
    const master_id = slice.loadInt(8);
    const owner_address = slice.loadAddress();
    return {
        $$type: 'BodyPayload2',
        master_id,
        owner_address,
    };
}

export function storeBodyPayload2(src: BodyPayload2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 2);
        builder.storeInt(src.master_id, 8);
        builder.storeAddress(src.owner_address);
    };
}

// === SayHiAndGoodbye ===
export const SayHiAndGoodbyeOpcode = 0x89;

export interface SayHiAndGoodbye {
    readonly $$type: 'SayHiAndGoodbye';
    dest_addr: Address | null;
    body: BodyPayload1 | BodyPayload2;
}

export function loadSayHiAndGoodbye(slice: Slice): SayHiAndGoodbye {
    if (slice.loadUint(8) !== 0x89) {
        throw new Error('Invalid opcode for SayHiAndGoodbye');
    }
    const dest_addr = slice.loadMaybeAddress();
    const body = (() => {
        const prefix = slice.preloadUint(3);
        if (prefix === 0x1) return loadBodyPayload1(slice);
        if (prefix === 0x1) return loadBodyPayload2(slice);
        throw new Error('Unknown union variant');
    })();
    return {
        $$type: 'SayHiAndGoodbye',
        dest_addr,
        body,
    };
}

export function storeSayHiAndGoodbye(src: SayHiAndGoodbye): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x89, 8);
        builder.storeAddress(src.dest_addr);
        (() => {
            if (src.body.$$type === 'BodyPayload1') storeBodyPayload1(src.body as BodyPayload1)(builder);
            else if (src.body.$$type === 'BodyPayload2') storeBodyPayload2(src.body as BodyPayload2)(builder);
            else throw new Error('Unknown union variant');
        })();
    };
}

// === SayStoreInChain ===
export const SayStoreInChainOpcode = 0x13;

export interface SayStoreInChain {
    readonly $$type: 'SayStoreInChain';
    in_masterchain: boolean;
    contents: Cell;
}

export function loadSayStoreInChain(slice: Slice): SayStoreInChain {
    if (slice.loadUint(16) !== 0x13) {
        throw new Error('Invalid opcode for SayStoreInChain');
    }
    const in_masterchain = slice.loadBoolean();
    const contents = slice.loadRef();
    return {
        $$type: 'SayStoreInChain',
        in_masterchain,
        contents,
    };
}

export function storeSayStoreInChain(src: SayStoreInChain): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x13, 16);
        builder.storeBit(src.in_masterchain);
        builder.storeRef(src.contents);
    };
}

// === TransferParams1 ===
export const TransferParams1Opcode = 0x794;

export interface TransferParams1 {
    readonly $$type: 'TransferParams1';
    dest_int: Address;
    amount: bigint;
    dest_ext: Address | ExternalAddress | null;
}

export function loadTransferParams1(slice: Slice): TransferParams1 {
    if (slice.loadUint(12) !== 0x794) {
        throw new Error('Invalid opcode for TransferParams1');
    }
    const dest_int = slice.loadAddress();
    const amount = slice.loadCoins();
    const dest_ext = slice.loadAddressAny();
    return {
        $$type: 'TransferParams1',
        dest_int,
        amount,
        dest_ext,
    };
}

export function storeTransferParams1(src: TransferParams1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x794, 12);
        builder.storeAddress(src.dest_int);
        builder.storeCoins(src.amount);
        builder.storeAddress(src.dest_ext);
    };
}

// === TransferParams2 ===
export const TransferParams2Opcode = 0x9;

export interface TransferParams2 {
    readonly $$type: 'TransferParams2';
    intVector: [number, bigint | null, bigint];
    needs_more: Cell;
}

export function loadTransferParams2(slice: Slice): TransferParams2 {
    if (slice.loadUint(4) !== 0x9) {
        throw new Error('Invalid opcode for TransferParams2');
    }
    const intVector = [slice.loadInt(32), slice.loadBit() ? slice.loadCoins() : null, slice.loadUintBig(64)];
    const needs_more = slice.loadRef();
    return {
        $$type: 'TransferParams2',
        intVector,
        needs_more,
    };
}

export function storeTransferParams2(src: TransferParams2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x9, 4);
        (() => { const t = src.intVector; builder.storeInt(t[0], 32); t[1] !== null ? (builder.storeBit(true), builder.storeCoins(t[1])) : builder.storeBit(false); builder.storeUint(t[2], 64); })();
        builder.storeRef(src.needs_more);
    };
}

// === MsgTransfer ===
export const MsgTransferOpcode = 0xfb3701ff;

export interface MsgTransfer {
    readonly $$type: 'MsgTransfer';
    params: EitherLeft<TransferParams> | EitherRight<Cell<TransferParams>>;
}

export function loadMsgTransfer(slice: Slice): MsgTransfer {
    if (slice.loadUint(32) !== 0xfb3701ff) {
        throw new Error('Invalid opcode for MsgTransfer');
    }
    const params = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return loadEitherLeft<TransferParams>(slice);
        if (tag === 1) return loadEitherRight<Cell<TransferParams>>(slice);
        throw new Error('Unknown union tag');
    })();
    return {
        $$type: 'MsgTransfer',
        params,
    };
}

export function storeMsgTransfer(src: MsgTransfer): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0xfb3701ff, 32);
        (() => {
            if ('EitherLeft<TransferParams>' in src.params) { builder.storeUint(0, 1); storeEitherLeft<TransferParams>(src.params)(builder); }
            else if ('EitherRight<Cell<TransferParams>>' in src.params) { builder.storeUint(1, 1); storeEitherRight<Cell<TransferParams>>(src.params)(builder); }
            else throw new Error('Unknown union variant');
        })();
    };
}

// === EitherLeft<TransferParams> ===
export interface EitherLeft<TransferParams> {
    value: TransferParams1 | TransferParams2;
}

export function loadEitherLeft<TransferParams>(slice: Slice): EitherLeft<TransferParams> {
    const value = (() => {
        const prefix = slice.preloadUint(12);
        if (prefix === 0x794) return loadTransferParams1(slice);
        if (prefix === 0x9) return loadTransferParams2(slice);
        throw new Error('Unknown union variant');
    })();
    return {
        value,
    };
}

export function storeEitherLeft<TransferParams>(src: EitherLeft<TransferParams>): (builder: Builder) => void {
    return (builder: Builder) => {
        (() => {
            if (src.value.$$type === 'TransferParams1') storeTransferParams1(src.value as TransferParams1)(builder);
            else if (src.value.$$type === 'TransferParams2') storeTransferParams2(src.value as TransferParams2)(builder);
            else throw new Error('Unknown union variant');
        })();
    };
}

// === EitherRight<Cell<TransferParams>> ===
export interface EitherRight<Cell<TransferParams>> {
    value: Cell;
}

export function loadEitherRight<Cell<TransferParams>>(slice: Slice): EitherRight<Cell<TransferParams>> {
    const value = slice.loadRef();
    return {
        value,
    };
}

export function storeEitherRight<Cell<TransferParams>>(src: EitherRight<Cell<TransferParams>>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.value);
    };
}

