
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress, BitString } from '@ton/core';

// === Color ===
export enum Color {
    Red = 0,
    Green = 1,
    Blue = 2
}

// === EInt9 ===
export enum EInt9 {
    P133 = 133,
    M1 = -1
}

// === EUint6 ===
export enum EUint6 {
    P63 = 63,
    P30 = 30,
    P1 = 1
}

// === EUint1 ===
export enum EUint1 {
    A = 0,
    B = 1
}

// === EInt1 ===
export enum EInt1 {
    A = -1,
    B = 0
}

// === EUint123 ===
export enum EUint123 {
    Z = 0,
    V5 = 5,
    E123 = 5316911983139663491615228241121378304,
    E123_2 = 7975367974709495237422842361682067456
}

// === JustInt32 ===
export interface JustInt32 {
    value: number;
}

export function loadJustInt32(slice: Slice): JustInt32 {
    const value = slice.loadInt(32);
    return {
        value,
    };
}

export function storeJustInt32(src: JustInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 32);
    };
}

// === JustMaybeInt32 ===
export interface JustMaybeInt32 {
    value: number | null;
}

export function loadJustMaybeInt32(slice: Slice): JustMaybeInt32 {
    const value = slice.loadBit() ? slice.loadInt(32) : null;
    return {
        value,
    };
}

export function storeJustMaybeInt32(src: JustMaybeInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        src.value !== null ? (builder.storeBit(true), builder.storeInt(src.value, 32)) : builder.storeBit(false);
    };
}

// === Test3_1 ===
export interface Test3_1 {
    f1: JustInt32;
    f2: JustMaybeInt32;
    f3: JustMaybeInt32;
    f4: JustInt32 | bigint;
}

export function loadTest3_1(slice: Slice): Test3_1 {
    const f1 = loadJustInt32(slice);
    const f2 = loadJustMaybeInt32(slice);
    const f3 = loadJustMaybeInt32(slice);
    const f4 = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return loadJustInt32(slice);
        if (tag === 1) return slice.loadUintBig(100);
        throw new Error('Unknown union tag');
    })();
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest3_1(src: Test3_1): (builder: Builder) => void {
    return (builder: Builder) => {
        storeJustInt32(src.f1)(builder);
        storeJustMaybeInt32(src.f2)(builder);
        storeJustMaybeInt32(src.f3)(builder);
        (() => {
            if ('JustInt32' in src.f4) { builder.storeUint(0, 1); storeJustInt32(src.f4)(builder); }
            else if (typeof src.f4 === 'bigint' || typeof src.f4 === 'number') { builder.storeUint(1, 1); builder.storeUint(src.f4, 100); }
            else throw new Error('Unknown union variant');
        })();
    };
}

// === Test3_2 ===
export interface Test3_2 {
    f1: Test3_1;
    f2: Test3_1 | null;
    f3: Test3_1 | null;
}

export function loadTest3_2(slice: Slice): Test3_2 {
    const f1 = loadTest3_1(slice);
    const f2 = slice.loadBit() ? loadTest3_1(slice) : null;
    const f3 = slice.loadBit() ? loadTest3_1(slice) : null;
    return {
        f1,
        f2,
        f3,
    };
}

export function storeTest3_2(src: Test3_2): (builder: Builder) => void {
    return (builder: Builder) => {
        storeTest3_1(src.f1)(builder);
        src.f2 !== null ? (builder.storeBit(true), storeTest3_1(src.f2)(builder)) : builder.storeBit(false);
        src.f3 !== null ? (builder.storeBit(true), storeTest3_1(src.f3)(builder)) : builder.storeBit(false);
    };
}

// === Test4_1 ===
export interface Test4_1 {
    f1: Address;
    f2: Address;
}

export function loadTest4_1(slice: Slice): Test4_1 {
    const f1 = slice.loadAddress();
    const f2 = slice.loadAddress();
    return {
        f1,
        f2,
    };
}

export function storeTest4_1(src: Test4_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.f1);
        builder.storeAddress(src.f2);
    };
}

// === Test4_2 ===
export interface Test4_2 {
    f1: Address | null;
    f2: Address | null;
}

export function loadTest4_2(slice: Slice): Test4_2 {
    const f1 = slice.loadMaybeAddress();
    const f2 = slice.loadMaybeAddress();
    return {
        f1,
        f2,
    };
}

export function storeTest4_2(src: Test4_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.f1);
        builder.storeAddress(src.f2);
    };
}

// === Test4_3 ===
export interface Test4_3 {
    f: [Test4_1, Test4_2];
}

export function loadTest4_3(slice: Slice): Test4_3 {
    const f = [loadTest4_1(slice), loadTest4_2(slice)];
    return {
        f,
    };
}

export function storeTest4_3(src: Test4_3): (builder: Builder) => void {
    return (builder: Builder) => {
        (() => { const t = src.f; storeTest4_1(t[0])(builder); storeTest4_2(t[1])(builder); })();
    };
}

// === Test5_1 ===
export interface Test5_1 {
    f1: Cell;
    f2: Cell | null;
    f3: Cell;
    f4: Cell | null;
}

export function loadTest5_1(slice: Slice): Test5_1 {
    const f1 = slice.loadRef();
    const f2 = slice.loadMaybeRef();
    const f3 = slice.loadRef();
    const f4 = slice.loadBit() ? slice.loadRef() : null;
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest5_1(src: Test5_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.f1);
        builder.storeMaybeRef(src.f2);
        builder.storeRef(src.f3);
        src.f4 !== null ? (builder.storeBit(true), builder.storeRef(src.f4)) : builder.storeBit(false);
    };
}

// === Test5_2 ===
export interface Test5_2 {
    f1: Cell | null;
    f2: Cell | null;
    f3: Cell | null;
    f4: Cell | null;
    f5: Cell | null;
    rest: Slice;
}

export function loadTest5_2(slice: Slice): Test5_2 {
    const f1 = slice.loadBit() ? slice.loadRef() : null;
    const f2 = slice.loadBit() ? slice.loadRef() : null;
    const f3 = slice.loadBit() ? slice.loadRef() : null;
    const f4 = slice.loadBit() ? slice.loadRef() : null;
    const f5 = slice.loadBit() ? slice.loadRef() : null;
    const rest = slice.clone();
    return {
        f1,
        f2,
        f3,
        f4,
        f5,
        rest,
    };
}

export function storeTest5_2(src: Test5_2): (builder: Builder) => void {
    return (builder: Builder) => {
        src.f1 !== null ? (builder.storeBit(true), builder.storeRef(src.f1)) : builder.storeBit(false);
        src.f2 !== null ? (builder.storeBit(true), builder.storeRef(src.f2)) : builder.storeBit(false);
        src.f3 !== null ? (builder.storeBit(true), builder.storeRef(src.f3)) : builder.storeBit(false);
        src.f4 !== null ? (builder.storeBit(true), builder.storeRef(src.f4)) : builder.storeBit(false);
        src.f5 !== null ? (builder.storeBit(true), builder.storeRef(src.f5)) : builder.storeBit(false);
        builder.storeSlice(src.rest);
    };
}

// === Test5_3 ===
export interface Test5_3 {
    f1: number | Cell;
    f2: Buffer | Cell;
    f3: Cell | Cell;
    f4: Cell | bigint;
}

export function loadTest5_3(slice: Slice): Test5_3 {
    const f1 = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return slice.loadInt(8);
        if (tag === 1) return loadCell<int8>(slice);
        throw new Error('Unknown union tag');
    })();
    const f2 = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return slice.loadBuffer(2);
        if (tag === 1) return loadCell<int16>(slice);
        throw new Error('Unknown union tag');
    })();
    const f3 = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return loadCell<int8>(slice);
        if (tag === 1) return slice.loadRef();
        throw new Error('Unknown union tag');
    })();
    const f4 = (() => {
        const tag = slice.loadUint(1);
        if (tag === 0) return loadCell<coins>(slice);
        if (tag === 1) return slice.loadCoins();
        throw new Error('Unknown union tag');
    })();
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeTest5_3(src: Test5_3): (builder: Builder) => void {
    return (builder: Builder) => {
        (() => {
            if (typeof src.f1 === 'bigint' || typeof src.f1 === 'number') { builder.storeUint(0, 1); builder.storeInt(src.f1, 8); }
            else if ('Cell<int8>' in src.f1) { builder.storeUint(1, 1); storeCell<int8>(src.f1)(builder); }
            else throw new Error('Unknown union variant');
        })();
        (() => {
            if (Buffer.isBuffer(src.f2) && src.f2.length === 2) { builder.storeUint(0, 1); builder.storeBuffer(src.f2); }
            else if ('Cell<int16>' in src.f2) { builder.storeUint(1, 1); storeCell<int16>(src.f2)(builder); }
            else throw new Error('Unknown union variant');
        })();
        (() => {
            if ('Cell<int8>' in src.f3) { builder.storeUint(0, 1); storeCell<int8>(src.f3)(builder); }
            else if (src.f3 instanceof Cell) { builder.storeUint(1, 1); builder.storeRef(src.f3); }
            else throw new Error('Unknown union variant');
        })();
        (() => {
            if ('Cell<coins>' in src.f4) { builder.storeUint(0, 1); storeCell<coins>(src.f4)(builder); }
            else if (typeof src.f4 === 'bigint' || typeof src.f4 === 'number') { builder.storeUint(1, 1); builder.storeCoins(src.f4); }
            else throw new Error('Unknown union variant');
        })();
    };
}

// === Test6_1 ===
export const Test6_1Opcode = 0x112233;

export interface Test6_1 {
    readonly $$type: 'Test6_1';
    f1: number;
}

export function loadTest6_1(slice: Slice): Test6_1 {
    if (slice.loadUint(32) !== 0x112233) {
        throw new Error('Invalid opcode for Test6_1');
    }
    const f1 = slice.loadInt(32);
    return {
        $$type: 'Test6_1',
        f1,
    };
}

export function storeTest6_1(src: Test6_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x112233, 32);
        builder.storeInt(src.f1, 32);
    };
}

// === Test6_2 ===
export const Test6_2Opcode = 0x2;

export interface Test6_2 {
    readonly $$type: 'Test6_2';
    f1: number | null;
    f2: Cell;
}

export function loadTest6_2(slice: Slice): Test6_2 {
    if (slice.loadUint(4) !== 0x2) {
        throw new Error('Invalid opcode for Test6_2');
    }
    const f1 = slice.loadBit() ? slice.loadInt(32) : null;
    const f2 = slice.loadRef();
    return {
        $$type: 'Test6_2',
        f1,
        f2,
    };
}

export function storeTest6_2(src: Test6_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x2, 4);
        src.f1 !== null ? (builder.storeBit(true), builder.storeInt(src.f1, 32)) : builder.storeBit(false);
        builder.storeRef(src.f2);
    };
}

// === Test7_1 ===
export const Test7_1Opcode = 0x1020;

export interface Test7_1 {
    readonly $$type: 'Test7_1';
}

export function loadTest7_1(slice: Slice): Test7_1 {
    if (slice.loadUint(16) !== 0x1020) {
        throw new Error('Invalid opcode for Test7_1');
    }
    return {
        $$type: 'Test7_1',
    };
}

export function storeTest7_1(src: Test7_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1020, 16);
    };
}

// === Test7_2 ===
export const Test7_2Opcode = 0x1030;

export interface Test7_2 {
    readonly $$type: 'Test7_2';
}

export function loadTest7_2(slice: Slice): Test7_2 {
    if (slice.loadUint(16) !== 0x1030) {
        throw new Error('Invalid opcode for Test7_2');
    }
    return {
        $$type: 'Test7_2',
    };
}

export function storeTest7_2(src: Test7_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1030, 16);
    };
}

// === Test7_3 ===
export const Test7_3Opcode = 0x1040;

export interface Test7_3 {
    readonly $$type: 'Test7_3';
}

export function loadTest7_3(slice: Slice): Test7_3 {
    if (slice.loadUint(16) !== 0x1040) {
        throw new Error('Invalid opcode for Test7_3');
    }
    return {
        $$type: 'Test7_3',
    };
}

export function storeTest7_3(src: Test7_3): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1040, 16);
    };
}

// === Inner8_1 ===
export const Inner8_1Opcode = 0x10;

export interface Inner8_1 {
    readonly $$type: 'Inner8_1';
    ea: Address | ExternalAddress | null;
}

export function loadInner8_1(slice: Slice): Inner8_1 {
    if (slice.loadUint(8) !== 0x10) {
        throw new Error('Invalid opcode for Inner8_1');
    }
    const ea = slice.loadAddressAny();
    return {
        $$type: 'Inner8_1',
        ea,
    };
}

export function storeInner8_1(src: Inner8_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x10, 8);
        builder.storeAddress(src.ea);
    };
}

// === CellInner8_1 ===
export const CellInner8_1Opcode = 0x1;

export interface CellInner8_1 {
    readonly $$type: 'CellInner8_1';
    ref: Cell;
}

export function loadCellInner8_1(slice: Slice): CellInner8_1 {
    if (slice.loadUint(1) !== 0x1) {
        throw new Error('Invalid opcode for CellInner8_1');
    }
    const ref = slice.loadRef();
    return {
        $$type: 'CellInner8_1',
        ref,
    };
}

export function storeCellInner8_1(src: CellInner8_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(0x1, 1);
        builder.storeRef(src.ref);
    };
}

// === Inner8_2 ===
export interface Inner8_2 {
    t: [Buffer, number, bigint | null];
}

export function loadInner8_2(slice: Slice): Inner8_2 {
    const t = [slice.loadBuffer(4), slice.loadInt(1), slice.loadBit() ? slice.loadCoins() : null];
    return {
        t,
    };
}

export function storeInner8_2(src: Inner8_2): (builder: Builder) => void {
    return (builder: Builder) => {
        (() => { const t = src.t; builder.storeBuffer(t[0]); builder.storeInt(t[1], 1); t[2] !== null ? (builder.storeBit(true), builder.storeCoins(t[2])) : builder.storeBit(false); })();
    };
}

// === Test8 ===
export interface Test8 {
    f1: Inner8_1;
    f2: Inner8_2;
    f3: Inner8_1 | null;
    f4: Inner8_2 | null;
    f5: Inner8_1 | CellInner8_1;
}

export function loadTest8(slice: Slice): Test8 {
    const f1 = loadInner8_1(slice);
    const f2 = loadInner8_2(slice);
    const f3 = slice.loadBit() ? loadInner8_1(slice) : null;
    const f4 = slice.loadBit() ? loadInner8_2(slice) : null;
    const f5 = (() => {
        const prefix = slice.preloadUint(8);
        if (prefix === 0x10) return loadInner8_1(slice);
        if (prefix === 0x1) return loadCellInner8_1(slice);
        throw new Error('Unknown union variant');
    })();
    return {
        f1,
        f2,
        f3,
        f4,
        f5,
    };
}

export function storeTest8(src: Test8): (builder: Builder) => void {
    return (builder: Builder) => {
        storeInner8_1(src.f1)(builder);
        storeInner8_2(src.f2)(builder);
        src.f3 !== null ? (builder.storeBit(true), storeInner8_1(src.f3)(builder)) : builder.storeBit(false);
        src.f4 !== null ? (builder.storeBit(true), storeInner8_2(src.f4)(builder)) : builder.storeBit(false);
        (() => {
            if (src.f5.$$type === 'Inner8_1') storeInner8_1(src.f5 as Inner8_1)(builder);
            else if (src.f5.$$type === 'CellInner8_1') storeCellInner8_1(src.f5 as CellInner8_1)(builder);
            else throw new Error('Unknown union variant');
        })();
    };
}

// === Test9_bits2 ===
export interface Test9_bits2 {
    f: BitString;
}

export function loadTest9_bits2(slice: Slice): Test9_bits2 {
    const f = slice.loadBits(2);
    return {
        f,
    };
}

export function storeTest9_bits2(src: Test9_bits2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.f);
    };
}

// === Test9_bits4 ===
export interface Test9_bits4 {
    f: BitString;
}

export function loadTest9_bits4(slice: Slice): Test9_bits4 {
    const f = slice.loadBits(4);
    return {
        f,
    };
}

export function storeTest9_bits4(src: Test9_bits4): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.f);
    };
}

// === Test10_1 ===
export interface Test10_1 {
    a: number;
    b: Builder;
}

export function loadTest10_1(slice: Slice): Test10_1 {
    const a = slice.loadInt(32);
    const b = /* cannot load builder */;
    return {
        a,
        b,
    };
}

export function storeTest10_1(src: Test10_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.a, 32);
        builder.storeBuilder(src.b);
    };
}

// === Test11_1 ===
export interface Test11_1 {
    data: BitString;
    next: Cell | null;
}

export function loadTest11_1(slice: Slice): Test11_1 {
    const data = slice.loadBits(1022);
    const next = slice.loadBit() ? slice.loadRef() : null;
    return {
        data,
        next,
    };
}

export function storeTest11_1(src: Test11_1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBits(src.data);
        src.next !== null ? (builder.storeBit(true), builder.storeRef(src.next)) : builder.storeBit(false);
    };
}

// === Test11_2 ===
export interface Test11_2 {
    self1: Cell;
    self2: Cell;
}

export function loadTest11_2(slice: Slice): Test11_2 {
    const self1 = slice.loadRef();
    const self2 = slice.loadRef();
    return {
        self1,
        self2,
    };
}

export function storeTest11_2(src: Test11_2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.self1);
        builder.storeRef(src.self2);
    };
}

// === JustAddress ===
export interface JustAddress {
    a: Address;
}

export function loadJustAddress(slice: Slice): JustAddress {
    const a = slice.loadAddress();
    return {
        a,
    };
}

export function storeJustAddress(src: JustAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.a);
    };
}

