
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell } from '@ton/core';

// === JustInt32 ===
export interface JustInt32 {
    value: number;
}

export function loadJustInt32(slice: Slice): JustInt32 {
    const value = slice.loadInt(32);
    return {
        value,
    };
}

export function storeJustInt32(src: JustInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 32);
    };
}

// === Point ===
export interface Point {
    x: number;
    y: number;
}

export function loadPoint(slice: Slice): Point {
    const x = slice.loadInt(32);
    const y = slice.loadInt(32);
    return {
        x,
        y,
    };
}

export function storePoint(src: Point): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.x, 32);
        builder.storeInt(src.y, 32);
    };
}

// === TwoU ===
export interface TwoU {
    a: number;
    b: number;
}

export function loadTwoU(slice: Slice): TwoU {
    const a = slice.loadUint(8);
    const b = slice.loadUint(8);
    return {
        a,
        b,
    };
}

export function storeTwoU(src: TwoU): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.a, 8);
        builder.storeUint(src.b, 8);
    };
}

