
/**
 * Auto-generated TypeScript bindings for Tolk structs.
 * Generated by Tolk compiler v1.2
 * 
 * @ton/core types are used for compatibility with the TON ecosystem.
 */

import { Builder, Slice, Cell, Address, ExternalAddress, Dictionary, BitString } from '@ton/core';

// === EStoredAsInt8 ===
export enum EStoredAsInt8 {
    M100 = -100,
    Z = 0,
    P100 = 100
}

// === EStoredAsUint1 ===
export enum EStoredAsUint1 {
    ZERO = 0,
    ONE = 1
}

// === MaybeNothing ===
export interface MaybeNothing {
}

export function loadMaybeNothing(slice: Slice): MaybeNothing {
    return {
    };
}

export function storeMaybeNothing(src: MaybeNothing): (builder: Builder) => void {
    return (builder: Builder) => {
    };
}

// === JustInt32 ===
export interface JustInt32 {
    value: number;
}

export function loadJustInt32(slice: Slice): JustInt32 {
    const value = slice.loadInt(32);
    return {
        value,
    };
}

export function storeJustInt32(src: JustInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 32);
    };
}

// === JustMaybeInt32 ===
export interface JustMaybeInt32 {
    value: number | null;
}

export function loadJustMaybeInt32(slice: Slice): JustMaybeInt32 {
    const value = slice.loadBit() ? slice.loadInt(32) : null;
    return {
        value,
    };
}

export function storeJustMaybeInt32(src: JustMaybeInt32): (builder: Builder) => void {
    return (builder: Builder) => {
        src.value !== null ? (builder.storeBit(true), builder.storeInt(src.value, 32)) : builder.storeBit(false);
    };
}

// === TwoInts32AndCoins ===
export interface TwoInts32AndCoins {
    op: number;
    amount: bigint;
}

export function loadTwoInts32AndCoins(slice: Slice): TwoInts32AndCoins {
    const op = slice.loadInt(32);
    const amount = slice.loadCoins();
    return {
        op,
        amount,
    };
}

export function storeTwoInts32AndCoins(src: TwoInts32AndCoins): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeCoins(src.amount);
    };
}

// === TwoInts32And64 ===
export interface TwoInts32And64 {
    op: number;
    query_id: bigint;
}

export function loadTwoInts32And64(slice: Slice): TwoInts32And64 {
    const op = slice.loadInt(32);
    const query_id = slice.loadUintBig(64);
    return {
        op,
        query_id,
    };
}

export function storeTwoInts32And64(src: TwoInts32And64): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeUint(src.query_id, 64);
    };
}

// === TwoInts32AndRef64 ===
export interface TwoInts32AndRef64 {
    op: number;
    query_id_ref: Cell;
}

export function loadTwoInts32AndRef64(slice: Slice): TwoInts32AndRef64 {
    const op = slice.loadInt(32);
    const query_id_ref = slice.loadRef();
    return {
        op,
        query_id_ref,
    };
}

export function storeTwoInts32AndRef64(src: TwoInts32AndRef64): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeRef(src.query_id_ref);
    };
}

// === TwoInts32AndMaybe64 ===
export interface TwoInts32AndMaybe64 {
    op: number;
    query_id: bigint | null;
    demo_bool_field: boolean;
}

export function loadTwoInts32AndMaybe64(slice: Slice): TwoInts32AndMaybe64 {
    const op = slice.loadInt(32);
    const query_id = slice.loadBit() ? slice.loadUintBig(64) : null;
    const demo_bool_field = slice.loadBoolean();
    return {
        op,
        query_id,
        demo_bool_field,
    };
}

export function storeTwoInts32AndMaybe64(src: TwoInts32AndMaybe64): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        src.query_id !== null ? (builder.storeBit(true), builder.storeUint(src.query_id, 64)) : builder.storeBit(false);
        builder.storeBit(src.demo_bool_field);
    };
}

// === JustAddress ===
export interface JustAddress {
    addr: Address;
}

export function loadJustAddress(slice: Slice): JustAddress {
    const addr = slice.loadAddress();
    return {
        addr,
    };
}

export function storeJustAddress(src: JustAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.addr);
    };
}

// === TwoInts32And64SepByAddress ===
export interface TwoInts32And64SepByAddress {
    op: number;
    addr_e: Address | ExternalAddress | null;
    query_id: bigint;
}

export function loadTwoInts32And64SepByAddress(slice: Slice): TwoInts32And64SepByAddress {
    const op = slice.loadInt(32);
    const addr_e = slice.loadAddressAny();
    const query_id = slice.loadUintBig(64);
    return {
        op,
        addr_e,
        query_id,
    };
}

export function storeTwoInts32And64SepByAddress(src: TwoInts32And64SepByAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeAddress(src.addr_e);
        builder.storeUint(src.query_id, 64);
    };
}

// === IntAndEitherInt8Or256 ===
export interface IntAndEitherInt8Or256 {
    op: number;
    i8or256: number | bigint;
}

export function loadIntAndEitherInt8Or256(slice: Slice): IntAndEitherInt8Or256 {
    const op = slice.loadInt(32);
    const i8or256 = /* union load - check opcodes */;
    return {
        op,
        i8or256,
    };
}

export function storeIntAndEitherInt8Or256(src: IntAndEitherInt8Or256): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        /* union store - switch on $$type */;
    };
}

// === Inner1 ===
export interface Inner1 {
    query_id_ref: bigint;
}

export function loadInner1(slice: Slice): Inner1 {
    const query_id_ref = slice.loadUintBig(64);
    return {
        query_id_ref,
    };
}

export function storeInner1(src: Inner1): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.query_id_ref, 64);
    };
}

// === Inner2 ===
export interface Inner2 {
    i64_in_ref: bigint;
}

export function loadInner2(slice: Slice): Inner2 {
    const i64_in_ref = slice.loadIntBig(64);
    return {
        i64_in_ref,
    };
}

export function storeInner2(src: Inner2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.i64_in_ref, 64);
    };
}

// === IntAndEither32OrRef64 ===
export interface IntAndEither32OrRef64 {
    op: number;
    i32orRef: number | Cell;
    query_id_maybe_ref: Cell | null;
}

export function loadIntAndEither32OrRef64(slice: Slice): IntAndEither32OrRef64 {
    const op = slice.loadInt(32);
    const i32orRef = /* union load - check opcodes */;
    const query_id_maybe_ref = slice.loadBit() ? slice.loadRef() : null;
    return {
        op,
        i32orRef,
        query_id_maybe_ref,
    };
}

export function storeIntAndEither32OrRef64(src: IntAndEither32OrRef64): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        /* union store - switch on $$type */;
        src.query_id_maybe_ref !== null ? (builder.storeBit(true), builder.storeRef(src.query_id_maybe_ref)) : builder.storeBit(false);
    };
}

// === IntAndEither8OrMaybe256 ===
export interface IntAndEither8OrMaybe256 {
    value: EitherLeft<int8> | EitherRight<int256?>;
    op: number;
}

export function loadIntAndEither8OrMaybe256(slice: Slice): IntAndEither8OrMaybe256 {
    const value = /* union load - check opcodes */;
    const op = slice.loadInt(32);
    return {
        value,
        op,
    };
}

export function storeIntAndEither8OrMaybe256(src: IntAndEither8OrMaybe256): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        builder.storeInt(src.op, 32);
    };
}

// === IntAndEitherMaybe8Or256 ===
export interface IntAndEitherMaybe8Or256 {
    value: EitherLeft<int8?> | EitherRight<int256>;
    op: number;
}

export function loadIntAndEitherMaybe8Or256(slice: Slice): IntAndEitherMaybe8Or256 {
    const value = /* union load - check opcodes */;
    const op = slice.loadInt(32);
    return {
        value,
        op,
    };
}

export function storeIntAndEitherMaybe8Or256(src: IntAndEitherMaybe8Or256): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        builder.storeInt(src.op, 32);
    };
}

// === IntAndMaybeMaybe8 ===
export interface IntAndMaybeMaybe8 {
    value: MaybeNothing | MaybeJust<Maybe<int8>>;
    op: number;
}

export function loadIntAndMaybeMaybe8(slice: Slice): IntAndMaybeMaybe8 {
    const value = /* union load - check opcodes */;
    const op = slice.loadInt(32);
    return {
        value,
        op,
    };
}

export function storeIntAndMaybeMaybe8(src: IntAndMaybeMaybe8): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        builder.storeInt(src.op, 32);
    };
}

// === SomeBytesFields ===
export interface SomeBytesFields {
    f1: Buffer;
    f2: BitString;
    f3: BitString | null;
    f4: BitString | Buffer;
}

export function loadSomeBytesFields(slice: Slice): SomeBytesFields {
    const f1 = slice.loadBuffer(1);
    const f2 = slice.loadBits(3);
    const f3 = slice.loadBit() ? slice.loadBits(20) : null;
    const f4 = /* union load - check opcodes */;
    return {
        f1,
        f2,
        f3,
        f4,
    };
}

export function storeSomeBytesFields(src: SomeBytesFields): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeBuffer(src.f1);
        builder.storeBits(src.f2);
        src.f3 !== null ? (builder.storeBit(true), builder.storeBits(src.f3)) : builder.storeBit(false);
        /* union store - switch on $$type */;
    };
}

// === IntAndRestInlineCell ===
export interface IntAndRestInlineCell {
    op: number;
    rest: Slice;
}

export function loadIntAndRestInlineCell(slice: Slice): IntAndRestInlineCell {
    const op = slice.loadInt(32);
    const rest = slice.clone();
    return {
        op,
        rest,
    };
}

export function storeIntAndRestInlineCell(src: IntAndRestInlineCell): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeSlice(src.rest);
    };
}

// === IntAndRestRefCell ===
export interface IntAndRestRefCell {
    op: number;
    rest: Cell;
}

export function loadIntAndRestRefCell(slice: Slice): IntAndRestRefCell {
    const op = slice.loadInt(32);
    const rest = slice.loadRef();
    return {
        op,
        rest,
    };
}

export function storeIntAndRestRefCell(src: IntAndRestRefCell): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeRef(src.rest);
    };
}

// === IntAndRestEitherCellOrRefCell ===
export interface IntAndRestEitherCellOrRefCell {
    op: number;
    rest: Slice | Cell;
}

export function loadIntAndRestEitherCellOrRefCell(slice: Slice): IntAndRestEitherCellOrRefCell {
    const op = slice.loadInt(32);
    const rest = /* union load - check opcodes */;
    return {
        op,
        rest,
    };
}

export function storeIntAndRestEitherCellOrRefCell(src: IntAndRestEitherCellOrRefCell): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        /* union store - switch on $$type */;
    };
}

// === DifferentMaybeRefs ===
export interface DifferentMaybeRefs {
    op: number;
    ref1m: Cell | null;
    ref2m: Cell | null;
    ref3: Cell;
    ref4m32: Cell | null;
    query_id: bigint;
}

export function loadDifferentMaybeRefs(slice: Slice): DifferentMaybeRefs {
    const op = slice.loadInt(32);
    const ref1m = slice.loadMaybeRef();
    const ref2m = slice.loadMaybeRef();
    const ref3 = slice.loadRef();
    const ref4m32 = slice.loadBit() ? slice.loadRef() : null;
    const query_id = slice.loadIntBig(64);
    return {
        op,
        ref1m,
        ref2m,
        ref3,
        ref4m32,
        query_id,
    };
}

export function storeDifferentMaybeRefs(src: DifferentMaybeRefs): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.op, 32);
        builder.storeMaybeRef(src.ref1m);
        builder.storeMaybeRef(src.ref2m);
        builder.storeRef(src.ref3);
        src.ref4m32 !== null ? (builder.storeBit(true), builder.storeRef(src.ref4m32)) : builder.storeBit(false);
        builder.storeInt(src.query_id, 64);
    };
}

// === DifferentIntsWithMaybe ===
export interface DifferentIntsWithMaybe {
    ji: JustInt32;
    jmi: JustMaybeInt32;
    jiMaybe: JustInt32 | null;
    jmiMaybe: JustMaybeInt32 | null;
}

export function loadDifferentIntsWithMaybe(slice: Slice): DifferentIntsWithMaybe {
    const ji = loadJustInt32(slice);
    const jmi = loadJustMaybeInt32(slice);
    const jiMaybe = slice.loadBit() ? loadJustInt32(slice) : null;
    const jmiMaybe = /* complex nullable: JustMaybeInt32 | null */;
    return {
        ji,
        jmi,
        jiMaybe,
        jmiMaybe,
    };
}

export function storeDifferentIntsWithMaybe(src: DifferentIntsWithMaybe): (builder: Builder) => void {
    return (builder: Builder) => {
        storeJustInt32(src.ji)(builder);
        storeJustMaybeInt32(src.jmi)(builder);
        src.jiMaybe !== null ? (builder.storeBit(true), storeJustInt32(src.jiMaybe)(builder)) : builder.storeBit(false);
        /* complex nullable store */;
    };
}

// === DifferentMix1 ===
export interface DifferentMix1 {
    ja1: JustAddress;
    ja2m: JustAddress | null;
    ext_nn: Address | ExternalAddress | null;
    imm: IntAndMaybeMaybe8;
    tis: TwoInts32And64SepByAddress;
}

export function loadDifferentMix1(slice: Slice): DifferentMix1 {
    const ja1 = loadJustAddress(slice);
    const ja2m = slice.loadBit() ? loadJustAddress(slice) : null;
    const ext_nn = slice.loadAddressAny();
    const imm = loadIntAndMaybeMaybe8(slice);
    const tis = loadTwoInts32And64SepByAddress(slice);
    return {
        ja1,
        ja2m,
        ext_nn,
        imm,
        tis,
    };
}

export function storeDifferentMix1(src: DifferentMix1): (builder: Builder) => void {
    return (builder: Builder) => {
        storeJustAddress(src.ja1)(builder);
        src.ja2m !== null ? (builder.storeBit(true), storeJustAddress(src.ja2m)(builder)) : builder.storeBit(false);
        builder.storeAddress(src.ext_nn);
        storeIntAndMaybeMaybe8(src.imm)(builder);
        storeTwoInts32And64SepByAddress(src.tis)(builder);
    };
}

// === DifferentMix2 ===
export interface DifferentMix2 {
    iae: Cell;
    tic: TwoInts32AndCoins;
    rest: Slice;
}

export function loadDifferentMix2(slice: Slice): DifferentMix2 {
    const iae = slice.loadRef();
    const tic = loadTwoInts32AndCoins(slice);
    const rest = slice.clone();
    return {
        iae,
        tic,
        rest,
    };
}

export function storeDifferentMix2(src: DifferentMix2): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeRef(src.iae);
        storeTwoInts32AndCoins(src.tic)(builder);
        builder.storeSlice(src.rest);
    };
}

// === DifferentMix3 ===
export interface DifferentMix3 {
    bod: Cell | Cell;
    tim: TwoInts32AndCoins | null;
    pairm: unknown /* (int32, int64) */ | null;
}

export function loadDifferentMix3(slice: Slice): DifferentMix3 {
    const bod = /* union load - check opcodes */;
    const tim = /* complex nullable: TwoInts32AndCoins | null */;
    const pairm = /* complex nullable: unknown /* (int32, int64) */ | null */;
    return {
        bod,
        tim,
        pairm,
    };
}

export function storeDifferentMix3(src: DifferentMix3): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        /* complex nullable store */;
        /* complex nullable store */;
    };
}

// === WithVariadicInts ===
export interface WithVariadicInts {
    ui16: bigint;
    i16: bigint;
    ui32: bigint;
    i32: bigint;
}

export function loadWithVariadicInts(slice: Slice): WithVariadicInts {
    const ui16 = slice.loadVarUintBig(16);
    const i16 = slice.loadVarIntBig(16);
    const ui32 = slice.loadVarUintBig(32);
    const i32 = slice.loadVarIntBig(32);
    return {
        ui16,
        i16,
        ui32,
        i32,
    };
}

export function storeWithVariadicInts(src: WithVariadicInts): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeVarUint(src.ui16, 16);
        builder.storeVarInt(src.i16, 16);
        builder.storeVarUint(src.ui32, 32);
        builder.storeVarInt(src.i32, 32);
    };
}

// === EdgeCaseInts ===
export interface EdgeCaseInts {
    maxUint: bigint;
    maxInt: bigint;
    minInt: bigint;
}

export function loadEdgeCaseInts(slice: Slice): EdgeCaseInts {
    const maxUint = slice.loadUintBig(256);
    const maxInt = slice.loadIntBig(257);
    const minInt = slice.loadIntBig(257);
    return {
        maxUint,
        maxInt,
        minInt,
    };
}

export function storeEdgeCaseInts(src: EdgeCaseInts): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.maxUint, 256);
        builder.storeInt(src.maxInt, 257);
        builder.storeInt(src.minInt, 257);
    };
}

// === WriteWithBuilder ===
export interface WriteWithBuilder {
    f1: number;
    rest: Builder;
}

export function loadWriteWithBuilder(slice: Slice): WriteWithBuilder {
    const f1 = slice.loadInt(32);
    const rest = /* cannot load builder */;
    return {
        f1,
        rest,
    };
}

export function storeWriteWithBuilder(src: WriteWithBuilder): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeBuilder(src.rest);
    };
}

// === WriteWithSlice ===
export interface WriteWithSlice {
    f1: number;
    rest: Slice;
}

export function loadWriteWithSlice(slice: Slice): WriteWithSlice {
    const f1 = slice.loadInt(32);
    const rest = slice.clone();
    return {
        f1,
        rest,
    };
}

export function storeWriteWithSlice(src: WriteWithSlice): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeSlice(src.rest);
    };
}

// === ReadWrittenWithBuilder ===
export interface ReadWrittenWithBuilder {
    f1: number;
    someInt: number;
    someCell: Cell | null;
}

export function loadReadWrittenWithBuilder(slice: Slice): ReadWrittenWithBuilder {
    const f1 = slice.loadInt(32);
    const someInt = slice.loadUint(32);
    const someCell = slice.loadMaybeRef();
    return {
        f1,
        someInt,
        someCell,
    };
}

export function storeReadWrittenWithBuilder(src: ReadWrittenWithBuilder): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeUint(src.someInt, 32);
        builder.storeMaybeRef(src.someCell);
    };
}

// === Tail224 ===
export interface Tail224 {
    ji: JustInt32;
    addr: Address;
    ref1: Cell | null;
    ref2: Cell;
}

export function loadTail224(slice: Slice): Tail224 {
    const ji = loadJustInt32(slice);
    const addr = slice.loadAddress();
    const ref1 = slice.loadBit() ? slice.loadRef() : null;
    const ref2 = slice.loadRef();
    return {
        ji,
        addr,
        ref1,
        ref2,
    };
}

export function storeTail224(src: Tail224): (builder: Builder) => void {
    return (builder: Builder) => {
        storeJustInt32(src.ji)(builder);
        builder.storeAddress(src.addr);
        src.ref1 !== null ? (builder.storeBit(true), builder.storeRef(src.ref1)) : builder.storeBit(false);
        builder.storeRef(src.ref2);
    };
}

// === WithTwoRestFields ===
export interface WithTwoRestFields {
    i32: number;
    rest1: Slice;
    rest2: Slice;
}

export function loadWithTwoRestFields(slice: Slice): WithTwoRestFields {
    const i32 = slice.loadInt(32);
    const rest1 = slice.clone();
    const rest2 = slice.clone();
    return {
        i32,
        rest1,
        rest2,
    };
}

export function storeWithTwoRestFields(src: WithTwoRestFields): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.i32, 32);
        builder.storeSlice(src.rest1);
        builder.storeSlice(src.rest2);
    };
}

// === WithMaps ===
export interface WithMaps {
    m1: Dictionary<number, Slice>;
    m2: Dictionary<JustInt32, unknown /* (int8, int8) */>;
}

export function loadWithMaps(slice: Slice): WithMaps {
    const m1 = Dictionary.load(/* key dict, value dict */);
    const m2 = Dictionary.load(/* key dict, value dict */);
    return {
        m1,
        m2,
    };
}

export function storeWithMaps(src: WithMaps): (builder: Builder) => void {
    return (builder: Builder) => {
        src.m1.store(builder);
        src.m2.store(builder);
    };
}

// === WithNullableMaps ===
export interface WithNullableMaps {
    m1: Dictionary<number, bigint> | null;
    m2: Dictionary<number, bigint> | null;
    m3: Dictionary<number, bigint> | null;
    m4: Dictionary<number, bigint> | number;
}

export function loadWithNullableMaps(slice: Slice): WithNullableMaps {
    const m1 = /* complex nullable: Dictionary<number, bigint> | null */;
    const m2 = /* complex nullable: Dictionary<number, bigint> | null */;
    const m3 = /* complex nullable: Dictionary<number, bigint> | null */;
    const m4 = /* union load - check opcodes */;
    return {
        m1,
        m2,
        m3,
        m4,
    };
}

export function storeWithNullableMaps(src: WithNullableMaps): (builder: Builder) => void {
    return (builder: Builder) => {
        /* complex nullable store */;
        /* complex nullable store */;
        /* complex nullable store */;
        /* union store - switch on $$type */;
    };
}

// === WithEnums ===
export interface WithEnums {
    e1: EStoredAsInt8;
    e2: EStoredAsUint1;
    rem: number;
}

export function loadWithEnums(slice: Slice): WithEnums {
    const e1 = slice.loadUint(32) as EStoredAsInt8;
    const e2 = slice.loadUint(32) as EStoredAsUint1;
    const rem = slice.loadUint(7);
    return {
        e1,
        e2,
        rem,
    };
}

export function storeWithEnums(src: WithEnums): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeUint(src.e1, 32);
        builder.storeUint(src.e2, 32);
        builder.storeUint(src.rem, 7);
    };
}

// === WithMoreTrickyAddresses1 ===
export interface WithMoreTrickyAddresses1 {
    a1: Address | null;
    a2: Address | number | MaybeNothing;
    a3: TwoInts32And64 | MaybeJust<address>;
    a4: Cell | null;
    a5: Address | Cell;
}

export function loadWithMoreTrickyAddresses1(slice: Slice): WithMoreTrickyAddresses1 {
    const a1 = slice.loadBit() ? slice.loadAddress() : null;
    const a2 = /* union load - check opcodes */;
    const a3 = /* union load - check opcodes */;
    const a4 = slice.loadBit() ? slice.loadRef() : null;
    const a5 = /* union load - check opcodes */;
    return {
        a1,
        a2,
        a3,
        a4,
        a5,
    };
}

export function storeWithMoreTrickyAddresses1(src: WithMoreTrickyAddresses1): (builder: Builder) => void {
    return (builder: Builder) => {
        src.a1 !== null ? (builder.storeBit(true), builder.storeAddress(src.a1)) : builder.storeBit(false);
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        src.a4 !== null ? (builder.storeBit(true), builder.storeRef(src.a4)) : builder.storeBit(false);
        /* union store - switch on $$type */;
    };
}

// === WithMoreTrickyAddresses2 ===
export interface WithMoreTrickyAddresses2 {
    a1: MaybeNothing | MaybeJust<address>;
    a2: MaybeNothing | MaybeJust<address?>;
    a3: JustAddress | null;
    a4: Address | bigint | unknown /* null */;
    a5: Address | Cell;
}

export function loadWithMoreTrickyAddresses2(slice: Slice): WithMoreTrickyAddresses2 {
    const a1 = /* union load - check opcodes */;
    const a2 = /* union load - check opcodes */;
    const a3 = slice.loadBit() ? loadJustAddress(slice) : null;
    const a4 = /* union load - check opcodes */;
    const a5 = /* union load - check opcodes */;
    return {
        a1,
        a2,
        a3,
        a4,
        a5,
    };
}

export function storeWithMoreTrickyAddresses2(src: WithMoreTrickyAddresses2): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        src.a3 !== null ? (builder.storeBit(true), storeJustAddress(src.a3)(builder)) : builder.storeBit(false);
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
    };
}

// === WithAnyAddress ===
export interface WithAnyAddress {
    a1: Address | ExternalAddress | null;
    a2: Address | ExternalAddress | null | null;
    a3: Address | ExternalAddress | null | bigint;
    a4: Address | Address | ExternalAddress | null;
    a5: MaybeNothing | MaybeJust<any_address>;
    a6: Cell;
    a7: Cell | null;
}

export function loadWithAnyAddress(slice: Slice): WithAnyAddress {
    const a1 = slice.loadAddressAny();
    const a2 = slice.loadMaybeAddress();
    const a3 = /* union load - check opcodes */;
    const a4 = /* union load - check opcodes */;
    const a5 = /* union load - check opcodes */;
    const a6 = slice.loadRef();
    const a7 = slice.loadBit() ? slice.loadRef() : null;
    return {
        a1,
        a2,
        a3,
        a4,
        a5,
        a6,
        a7,
    };
}

export function storeWithAnyAddress(src: WithAnyAddress): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.a1);
        builder.storeAddress(src.a2);
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        /* union store - switch on $$type */;
        builder.storeRef(src.a6);
        src.a7 !== null ? (builder.storeBit(true), builder.storeRef(src.a7)) : builder.storeBit(false);
    };
}

// === EitherLeft<int8> ===
export interface EitherLeft<int8> {
    value: number;
}

export function loadEitherLeft<int8>(slice: Slice): EitherLeft<int8> {
    const value = slice.loadInt(8);
    return {
        value,
    };
}

export function storeEitherLeft<int8>(src: EitherLeft<int8>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 8);
    };
}

// === EitherRight<int256?> ===
export interface EitherRight<int256?> {
    value: bigint | null;
}

export function loadEitherRight<int256?>(slice: Slice): EitherRight<int256?> {
    const value = slice.loadBit() ? slice.loadIntBig(256) : null;
    return {
        value,
    };
}

export function storeEitherRight<int256?>(src: EitherRight<int256?>): (builder: Builder) => void {
    return (builder: Builder) => {
        src.value !== null ? (builder.storeBit(true), builder.storeInt(src.value, 256)) : builder.storeBit(false);
    };
}

// === EitherLeft<int8?> ===
export interface EitherLeft<int8?> {
    value: number | null;
}

export function loadEitherLeft<int8?>(slice: Slice): EitherLeft<int8?> {
    const value = slice.loadBit() ? slice.loadInt(8) : null;
    return {
        value,
    };
}

export function storeEitherLeft<int8?>(src: EitherLeft<int8?>): (builder: Builder) => void {
    return (builder: Builder) => {
        src.value !== null ? (builder.storeBit(true), builder.storeInt(src.value, 8)) : builder.storeBit(false);
    };
}

// === EitherRight<int256> ===
export interface EitherRight<int256> {
    value: bigint;
}

export function loadEitherRight<int256>(slice: Slice): EitherRight<int256> {
    const value = slice.loadIntBig(256);
    return {
        value,
    };
}

export function storeEitherRight<int256>(src: EitherRight<int256>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 256);
    };
}

// === MaybeJust<int8> ===
export interface MaybeJust<int8> {
    value: number;
}

export function loadMaybeJust<int8>(slice: Slice): MaybeJust<int8> {
    const value = slice.loadInt(8);
    return {
        value,
    };
}

export function storeMaybeJust<int8>(src: MaybeJust<int8>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.value, 8);
    };
}

// === MaybeJust<Maybe<int8>> ===
export interface MaybeJust<Maybe<int8>> {
    value: MaybeNothing | MaybeJust<int8>;
}

export function loadMaybeJust<Maybe<int8>>(slice: Slice): MaybeJust<Maybe<int8>> {
    const value = /* union load - check opcodes */;
    return {
        value,
    };
}

export function storeMaybeJust<Maybe<int8>>(src: MaybeJust<Maybe<int8>>): (builder: Builder) => void {
    return (builder: Builder) => {
        /* union store - switch on $$type */;
    };
}

// === ReadWriteRest<RemainingBitsAndRefs> ===
export interface ReadWriteRest<RemainingBitsAndRefs> {
    f1: number;
    f2: bigint;
    rest: Slice;
}

export function loadReadWriteRest<RemainingBitsAndRefs>(slice: Slice): ReadWriteRest<RemainingBitsAndRefs> {
    const f1 = slice.loadInt(32);
    const f2 = slice.loadCoins();
    const rest = slice.clone();
    return {
        f1,
        f2,
        rest,
    };
}

export function storeReadWriteRest<RemainingBitsAndRefs>(src: ReadWriteRest<RemainingBitsAndRefs>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeCoins(src.f2);
        builder.storeSlice(src.rest);
    };
}

// === MaybeJust<address> ===
export interface MaybeJust<address> {
    value: Address;
}

export function loadMaybeJust<address>(slice: Slice): MaybeJust<address> {
    const value = slice.loadAddress();
    return {
        value,
    };
}

export function storeMaybeJust<address>(src: MaybeJust<address>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.value);
    };
}

// === MaybeJust<address?> ===
export interface MaybeJust<address?> {
    value: Address | null;
}

export function loadMaybeJust<address?>(slice: Slice): MaybeJust<address?> {
    const value = slice.loadMaybeAddress();
    return {
        value,
    };
}

export function storeMaybeJust<address?>(src: MaybeJust<address?>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.value);
    };
}

// === MaybeJust<any_address> ===
export interface MaybeJust<any_address> {
    value: Address | ExternalAddress | null;
}

export function loadMaybeJust<any_address>(slice: Slice): MaybeJust<any_address> {
    const value = slice.loadAddressAny();
    return {
        value,
    };
}

export function storeMaybeJust<any_address>(src: MaybeJust<any_address>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeAddress(src.value);
    };
}

// === ReadWriteRest<builder> ===
export interface ReadWriteRest<builder> {
    f1: number;
    f2: bigint;
    rest: Builder;
}

export function loadReadWriteRest<builder>(slice: Slice): ReadWriteRest<builder> {
    const f1 = slice.loadInt(32);
    const f2 = slice.loadCoins();
    const rest = /* cannot load builder */;
    return {
        f1,
        f2,
        rest,
    };
}

export function storeReadWriteRest<builder>(src: ReadWriteRest<builder>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeCoins(src.f2);
        builder.storeBuilder(src.rest);
    };
}

// === ReadWriteMid<bits40> ===
export interface ReadWriteMid<bits40> {
    f1: number;
    mid: Buffer;
    f3: bigint;
}

export function loadReadWriteMid<bits40>(slice: Slice): ReadWriteMid<bits40> {
    const f1 = slice.loadInt(32);
    const mid = slice.loadBuffer(5);
    const f3 = slice.loadCoins();
    return {
        f1,
        mid,
        f3,
    };
}

export function storeReadWriteMid<bits40>(src: ReadWriteMid<bits40>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeBuffer(src.mid);
        builder.storeCoins(src.f3);
    };
}

// === ReadWriteMid<builder> ===
export interface ReadWriteMid<builder> {
    f1: number;
    mid: Builder;
    f3: bigint;
}

export function loadReadWriteMid<builder>(slice: Slice): ReadWriteMid<builder> {
    const f1 = slice.loadInt(32);
    const mid = /* cannot load builder */;
    const f3 = slice.loadCoins();
    return {
        f1,
        mid,
        f3,
    };
}

export function storeReadWriteMid<builder>(src: ReadWriteMid<builder>): (builder: Builder) => void {
    return (builder: Builder) => {
        builder.storeInt(src.f1, 32);
        builder.storeBuilder(src.mid);
        builder.storeCoins(src.f3);
    };
}

