/*
    This file is part of TON Blockchain source code.

    TON Blockchain is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    TON Blockchain is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with TON Blockchain.  If not, see <http://www.gnu.org/licenses/>.

    In addition, as a special exception, the copyright holders give permission
    to link the code of portions of this program with the OpenSSL library.
    You must obey the GNU General Public License in all respects for all
    of the code used other than OpenSSL. If you modify file(s) with this
    exception, you may extend this exception to your version of the file(s),
    but you are not obligated to do so. If you do not wish to do so, delete this
    exception statement from your version. If you delete this exception statement
    from all source files in the program, then also delete it here.

    Copyright 2017-2020 Telegram Systems LLP
*/
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "td/tl/tl_config.h"
#include "td/tl/tl_core.h"
#include "td/tl/tl_file_outputer.h"
#include "td/tl/tl_generate.h"
#include "td/tl/tl_writer.h"

#include "tl_json_converter.h"
#include "tl_writer_cpp.h"
#include "tl_writer_h.h"
#include "tl_writer_hpp.h"
#include "tl_writer_jni_cpp.h"
#include "tl_writer_jni_h.h"

template <class WriterCpp = td::TD_TL_writer_cpp, class WriterH = td::TD_TL_writer_h,
          class WriterHpp = td::TD_TL_writer_hpp>
static void generate_cpp(const std::string &directory, const std::string &tl_name, const std::string &string_type,
                         const std::string &bytes_type, const std::string &secure_string_type,
                         const std::string &secure_bytes_type, const std::vector<std::string> &ext_cpp_includes,
                         const std::vector<std::string> &ext_h_includes) {
  std::string path = directory + "/" + tl_name;
  td::tl::tl_config config = td::tl::read_tl_config_from_file("scheme/" + tl_name + ".tlo");
  td::tl::write_tl_to_file(
      config, path + ".cpp",
      WriterCpp(tl_name, string_type, bytes_type, secure_string_type, secure_bytes_type, ext_cpp_includes));
  td::tl::write_tl_to_file(
      config, path + ".h",
      WriterH(tl_name, string_type, bytes_type, secure_string_type, secure_bytes_type, ext_h_includes));
  td::tl::write_tl_to_file(config, path + ".hpp",
                           WriterHpp(tl_name, string_type, bytes_type, secure_string_type, secure_bytes_type));
}

// Emits two files: <path>.h with a function declaration and <path>.cpp with a switch mapping
// every TL constructor and function ID known to `config` to its schema name. Used by the
// metrics layer so that traffic counters can be labeled by valid TL constructor name without
// turning random bytes from the wire into Prometheus label values.
//
// The header is intentionally tiny and stable: only the constructor list churns and only the
// .cpp recompiles when the schema changes.
static void generate_id_names(const std::string &directory, const std::string &tl_name) {
  td::tl::tl_config config = td::tl::read_tl_config_from_file("scheme/" + tl_name + ".tlo");

  // Collect (id, name) pairs, deduplicating by id (constructors and functions share an id space).
  std::map<std::int32_t, std::string> id_to_name;
  for (std::size_t i = 0; i < config.get_type_count(); i++) {
    auto *type = config.get_type_by_num(i);
    for (auto *combinator : type->constructors) {
      id_to_name.emplace(combinator->id, combinator->name);
    }
  }
  for (std::size_t i = 0; i < config.get_function_count(); i++) {
    auto *function = config.get_function_by_num(i);
    id_to_name.emplace(function->id, function->name);
  }

  std::string path = directory + "/" + tl_name + "_id_names";
  std::string fn_name = tl_name + "_id_name";

  td::tl::tl_file_outputer header;
  header.open(path + ".h");
  std::ostringstream h;
  h << "// Generated by tl/generate/generate_common.cpp. Do not edit.\n";
  h << "#pragma once\n\n";
  h << "#include \"td/utils/int_types.h\"\n\n";
  h << "namespace ton {\n";
  h << "// Returns the schema name of the TL constructor (or function) with the given id,\n";
  h << "// or nullptr if the id is not declared in the " << tl_name << " schema.\n";
  h << "const char *" << fn_name << "(td::int32 id);\n";
  h << "}  // namespace ton\n";
  header.append(h.str());

  td::tl::tl_file_outputer source;
  source.open(path + ".cpp");
  std::ostringstream c;
  c << "// Generated by tl/generate/generate_common.cpp. Do not edit.\n";
  c << "#include \"" << tl_name << "_id_names.h\"\n\n";
  c << "namespace ton {\n";
  c << "const char *" << fn_name << "(td::int32 id) {\n";
  c << "  switch (id) {\n";
  for (auto &[id, name] : id_to_name) {
    c << "    case " << id << ": return \"" << name << "\";\n";
  }
  c << "    default: return nullptr;\n";
  c << "  }\n";
  c << "}\n";
  c << "}  // namespace ton\n";
  source.append(c.str());
}

int main() {
  generate_cpp("auto/tl", "ton_api", "std::string", "td::BufferSlice", "std::string", "td::BufferSlice",
               {"\"tl/tl_object_parse.h\"", "\"tl/tl_object_store.h\"", "\"td/utils/int_types.h\"",
                "\"crypto/common/bitstring.h\""},
               {"<string>", "\"td/utils/buffer.h\"", "\"crypto/common/bitstring.h\""});
  generate_id_names("auto/tl", "ton_api");

  generate_cpp("auto/tl", "lite_api", "std::string", "td::BufferSlice", "std::string", "td::BufferSlice",
               {"\"tl/tl_object_parse.h\"", "\"tl/tl_object_store.h\"", "\"td/utils/int_types.h\"",
                "\"crypto/common/bitstring.h\""},
               {"<string>", "\"td/utils/buffer.h\"", "\"crypto/common/bitstring.h\""});
  td::gen_json_converter(td::tl::read_tl_config_from_file("scheme/ton_api.tlo"), "auto/tl/ton_api_json", "ton_api",
                         td::tl::TL_writer::Mode::All);

#ifdef TONLIB_ENABLE_JNI
  generate_cpp<td::TD_TL_writer_jni_cpp, td::TD_TL_writer_jni_h>(
      "auto/tl", "tonlib_api", "std::string", "std::string", "td::SecureString", "td::SecureString",
      {"\"tl/tl_jni_object.h\"", "\"tl/tl_object_store.h\"", "\"td/utils/int_types.h\""},
      {"<string>", "\"td/utils/SharedSlice.h\"", "\"crypto/common/bitstring.h\""});
#else
  generate_cpp<>("auto/tl", "tonlib_api", "std::string", "std::string", "td::SecureString", "td::SecureString",
                 {"\"tl/tl_object_parse.h\"", "\"tl/tl_object_store.h\"", "\"td/utils/int_types.h\""},
                 {"<string>", "\"td/utils/SharedSlice.h\"", "\"crypto/common/bitstring.h\""});
#endif
  td::gen_json_converter(td::tl::read_tl_config_from_file("scheme/tonlib_api.tlo"), "auto/tl/tonlib_api_json",
                         "tonlib_api", td::tl::TL_writer::Mode::All);
}
