name: MacOS-14 TON build (portable, arm64)

on:
  pull_request:
    branches: [master, testnet]
    types: [opened, reopened, synchronize]
  push:
    branches: [master, testnet]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'recursive'

      - name: Date Stamp
        shell: bash
        id: date-stamp
        run: |
          echo "timestamp=$(date -u "+%Y%m%d%H%M_%S")" >> "$GITHUB_OUTPUT"

      - name: Install ccache
        run: |
          brew install ccache
          mkdir -p ~/.ccache
          echo "CCACHE_DIR=$HOME/.ccache" >> "$GITHUB_ENV"

      - name: Restore cache TON
        id: cache-ton
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-14-portable-ccache-${{ steps.date-stamp.outputs.timestamp }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-14-portable-ccache

      - name: Build TON
        run: |
          git submodule sync --recursive
          git submodule update
          cp assembly/native/build-macos-portable.sh .
          chmod +x build-macos-portable.sh
          ./build-macos-portable.sh -t -a -c -o 14.0

      - name: Print ccache stats after TON build
        if: ${{ always() }}
        run: |
          ccache -sp
          ccache -z

      - name: Save cache TON
        if: ${{ success() }}
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.ccache
          key: ${{ steps.cache-ton.outputs.cache-primary-key }}

      - name: Delete restored cache TON
        if: ${{ success() && steps.cache-ton.outputs.cache-matched-key != '' && steps.cache-ton.outputs.cache-matched-key != steps.cache-ton.outputs.cache-primary-key }}
        env:
          GH_TOKEN: ${{ github.token }}
          CACHE_KEY: ${{ steps.cache-ton.outputs.cache-matched-key }}
        run: |
          echo "Deleting restored cache: ${CACHE_KEY} for ${GITHUB_REF}"
          gh cache delete "${CACHE_KEY}" --repo "${GITHUB_REPOSITORY}" --ref "${GITHUB_REF}" || true

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure --timeout 1800

      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ton-arm64-macos
          path: artifacts
          retention-days: 14
          if-no-files-found: error
