name: MacOS-13 TON build (portable, x86-64)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Date Stamp
        shell: bash
        id: date-stamp
        run: |
          echo "timestamp=$(date -u "+%Y%m%d%H%M_%S")" >> "$GITHUB_OUTPUT"

      - name: Create directories
        run: |
          mkdir -p ~/.ccache
          mkdir -p 3pp

      - name: Cache 3pp
        id: cache-3pp
        uses: actions/cache@v4
        with:
          path: 3pp
          key: ${{ runner.os }}-${{ runner.arch }}-13-3pp-${{ hashFiles('**/assembly/native/build-macos-portable.sh') }}

      - name: Cache TON test
        id: cache-ton
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-${{ runner.arch }}-13-portable-ccache-${{ steps.date-stamp.outputs.timestamp }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-13-portable-ccache

      - name: Build TON
        run: |
          git submodule sync --recursive
          git submodule update
          cp assembly/native/build-macos-portable.sh .
          chmod +x build-macos-portable.sh
          ./build-macos-portable.sh -t -a -c -o 13.0
          ccache -sp

      - name: Run Tests
        run: |
          cd build        
          ctest --output-on-failure --timeout 1800

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton-x86_64-macos
          path: artifacts
