name: Clear all GH cache

on:
  workflow_dispatch

jobs:
  clear-cache:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Clear all cache
        run: gh cache delete --all
