name: Create tolk release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tolk release and tag name'
        required: true

permissions: write-all

jobs:
  # Download artifacts in parallel for better performance
  download-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Download all artifacts in parallel (only unpacked versions needed)
      - name: Download Linux arm64 artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-ton-linux-arm64-appimage.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: false

      - name: Download Linux x86-64 artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-ton-linux-x86-64-appimage.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: false

      - name: Download Mac x86-64 artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-ton-macos-13-x86-64-portable.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: false

      - name: Download Mac arm64 artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-ton-macos-14-arm64-portable.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: false

      - name: Download Windows artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ton-x86-64-windows.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: false

      - name: Download WASM artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-ton-wasm-emscripten.yml
          path: artifacts
          workflow_conclusion: success
          branch: master
          skip_unpack: true

      - name: Show all artifacts
        run: |
          tree artifacts || ls -la artifacts

      - name: Upload artifacts for release job
        uses: actions/upload-artifact@v4
        with:
          name: tolk-release-artifacts
          path: artifacts

  create-release:
    runs-on: ubuntu-22.04
    needs: download-artifacts
    steps:
      - uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: tolk-release-artifacts
          path: artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          draft: false
          prerelease: false

      # Batch upload all tolk binaries using gh CLI for efficiency
      - name: Upload all tolk binaries
        run: |
          TAG="${{ inputs.tag }}"
          
          # Upload all tolk binaries in one efficient command
          gh release upload "$TAG" --repo ${{ github.repository }} \
            artifacts/ton-x86-64-windows/tolk.exe \
            artifacts/ton-x86_64-macos/tolk#tolk-mac-x86-64 \
            artifacts/ton-arm64-macos/tolk#tolk-mac-arm64 \
            artifacts/ton-x86_64-linux/tolk#tolk-linux-x86_64 \
            artifacts/ton-arm64-linux/tolk#tolk-linux-arm64 \
            artifacts/ton-wasm.zip

